# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Apr 21 13:03:27 2023
# ------------------------------------------------

package:
  name: libxcb
  version: '1.15'
source:
  fn: libxcb-1.15.tar.bz2
  patches: null
  sha256: 1cb65df8543a69ec0555ac696123ee386321dfac1964a3da39976c9a05ad724d
  url: https://xorg.freedesktop.org/archive/individual/lib/libxcb-1.15.tar.gz
build:
  detect_binary_files_with_prefix: true
  number: '0'
  run_exports:
    - libxcb >=1.15,<1.16.0a0
  string: hf346824_0
requirements:
  build:
    - autoconf 2.71 pl5321hed12c24_1
    - automake 1.16.5 pl5321h694c41f_0
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2022.12.7 h033912b_0
    - cctools_osx-64 973.0.1 hcc6d90d_13
    - cctools_osx-arm64 973.0.1 hfd1dfa6_13
    - clang 14.0.6 h694c41f_0
    - clang-14 14.0.6 default_h55ffa42_0
    - clang_osx-arm64 14.0.6 he41d1a2_6
    - clangxx 14.0.6 default_h55ffa42_0
    - compiler-rt 14.0.6 h613da45_0
    - compiler-rt_osx-64 14.0.6 hab78ec2_0
    - gettext 0.21.1 h8a4c099_0
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - ld64_osx-64 609 hfd63004_13
    - ld64_osx-arm64 609 h566df06_13
    - libclang-cpp14 14.0.6 default_h55ffa42_0
    - libcxx 16.0.1 h71dddab_0
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.17 hac89ed1_0
    - libllvm14 14.0.6 h5b596cc_1
    - libsqlite 3.40.0 ha978bb4_0
    - libtool 2.4.7 hf0c8a7f_0
    - libzlib 1.2.13 hfd90126_4
    - llvm-tools 14.0.6 h5b596cc_1
    - m4 1.4.18 haf1e3a3_1001
    - make 4.3 h22f3db7_1
    - ncurses 6.3 h96cf925_1
    - openssl 3.1.0 hfd90126_0
    - perl 5.32.1 2_h0d85af4_perl5
    - pkg-config 0.29.2 ha3d46e9_1008
    - python 3.10.10 he7542f4_0_cpython
    - readline 8.2 h9e318b2_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2023c h71feb2d_0
    - xz 5.2.6 h775f41a_0
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2022.12.7 h4653dfc_0
    - libexpat 2.5.0 hb7217d7_1
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.40.0 h76d750c_0
    - libzlib 1.2.13 h03a7124_4
    - ncurses 6.3 h07bb92c_1
    - openssl 3.1.0 h03a7124_0
    - pthread-stubs 0.4 h27ca646_1001
    - python 3.11.3 h1456518_0_cpython
    - python_abi 3.11 3_cp311
    - readline 8.2 h92ec313_1
    - tk 8.6.12 he1e0b03_0
    - tzdata 2023c h71feb2d_0
    - xcb-proto 1.15 py311heffc1b2_1
    - xorg-libxau 1.0.9 h27ca646_0
    - xorg-libxdmcp 1.1.3 h27ca646_0
    - xorg-util-macros 1.19.3 h27ca646_0
    - xorg-xproto 7.0.31 h27ca646_1007
    - xz 5.2.6 h57fd34a_0
  run:
    - pthread-stubs
    - xorg-libxau
    - xorg-libxdmcp
test:
  commands:
    - test -f $PREFIX/lib/libxcb.dylib
    - test -f $PREFIX/lib/libxcb-composite.dylib
    - test -f $PREFIX/lib/libxcb-damage.dylib
    - test -f $PREFIX/lib/libxcb-dpms.dylib
    - test -f $PREFIX/lib/libxcb-dri2.dylib
    - test -f $PREFIX/lib/libxcb-glx.dylib
    - test -f $PREFIX/lib/libxcb-present.dylib
    - test -f $PREFIX/lib/libxcb-randr.dylib
    - test -f $PREFIX/lib/libxcb-record.dylib
    - test -f $PREFIX/lib/libxcb-res.dylib
    - test -f $PREFIX/lib/libxcb-screensaver.dylib
    - test -f $PREFIX/lib/libxcb-shape.dylib
    - test -f $PREFIX/lib/libxcb-shm.dylib
    - test -f $PREFIX/lib/libxcb-sync.dylib
    - test -f $PREFIX/lib/libxcb-xf86dri.dylib
    - test -f $PREFIX/lib/libxcb-xfixes.dylib
    - test -f $PREFIX/lib/libxcb-xinerama.dylib
    - test -f $PREFIX/lib/libxcb-xkb.dylib
    - test -f $PREFIX/lib/libxcb-xtest.dylib
    - test -f $PREFIX/lib/libxcb-xv.dylib
    - test -f $PREFIX/lib/libxcb-xvmc.dylib
    - test -f $PREFIX/lib/libxcb-dri3.dylib
    - test -f $PREFIX/lib/libxcb-render.dylib
    - test -f $PREFIX/lib/libxcb-xinput.dylib
about:
  home: http://xcb.freedesktop.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: This is the C-language Binding (XCB) package to the X Window System protocol
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - pkgw
