# This file created by conda-build 3.23.3
# ------------------------------------------------

package:
  name: libnghttp2
  version: 1.52.0
source:
  sha256: 9877caa62bd72dde1331da38ce039dadb049817a01c3bdee809da15b754771b8
  url: https://github.com/nghttp2/nghttp2/releases/download/v1.52.0/nghttp2-1.52.0.tar.gz
build:
  number: 0
  run_exports:
    - libnghttp2 >=1.52.0,<2.0a0
  string: hae82a92_0
requirements:
  build:
    - ca-certificates 2022.12.7 h033912b_0
    - cctools_osx-64 973.0.1 hcc6d90d_11
    - cctools_osx-arm64 973.0.1 hfd1dfa6_11
    - clang 14.0.6 h694c41f_0
    - clang-14 14.0.6 default_h55ffa42_0
    - clang_osx-arm64 14.0.6 he41d1a2_4
    - clangxx 14.0.6 default_h55ffa42_0
    - clangxx_osx-arm64 14.0.6 h748fd88_4
    - compiler-rt 14.0.6 h613da45_0
    - compiler-rt_osx-64 14.0.6 hab78ec2_0
    - ld64_osx-64 609 hfd63004_11
    - ld64_osx-arm64 609 h566df06_11
    - libclang-cpp14 14.0.6 default_h55ffa42_0
    - libcxx 15.0.7 h71dddab_0
    - libllvm14 14.0.6 h5b596cc_1
    - libzlib 1.2.13 hfd90126_4
    - llvm-tools 14.0.6 h5b596cc_1
    - make 4.3 h22f3db7_1
    - openssl 3.0.8 hfd90126_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
  host:
    - c-ares 1.18.1 h3422bc3_0
    - ca-certificates 2022.12.7 h4653dfc_0
    - libcxx 15.0.7 h75e25f2_0
    - libev 4.33 h642e427_1
    - libzlib 1.2.13 h03a7124_4
    - openssl 3.0.8 h03a7124_0
    - zlib 1.2.13 h03a7124_4
  run:
    - c-ares >=1.18.1,<2.0a0
    - libcxx >=14.0.6
    - libev >=4.33,<4.34.0a0
    - libzlib >=1.2.13,<1.3.0a0
    - openssl >=3.0.8,<4.0a0
test:
  commands:
    - nghttp -nv https://nghttp2.org
    - test ! -f ${PREFIX}/lib/libnghttp2.a
about:
  description: 'This is an implementation of the Hypertext Transfer Protocol version
    2 in C.


    The framing layer of HTTP/2 is implemented as a reusable C library. On top

    of that, we have implemented an HTTP/2 client, server and proxy. We have

    also developed load test and benchmarking tools for HTTP/2.

    '
  dev_url: https://github.com/nghttp2/nghttp2
  doc_url: https://nghttp2.org/documentation/
  home: http://github.com/nghttp2/nghttp2
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: This is an implementation of Hypertext Transfer Protocol version 2.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - cpaulik
    - mariusvniekerk
    - wolfv
