# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Thu Sep 14 16:14:46 2023
# ------------------------------------------------

package:
  name: openjpeg
  version: 2.5.0
source:
  sha256: 0333806d6adecc6f7a91243b2b839ff4d2053823634d4f6ed7a59bc87409122a
  url: https://github.com/uclouvain/openjpeg/archive/v2.5.0.tar.gz
build:
  number: '3'
  run_exports:
    - openjpeg >=2.5.0,<3.0a0
  string: h4c1507b_3
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - c-ares 1.19.1 h0dc2134_0
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 habff3f6_14
    - cctools_osx-arm64 973.0.1 h2f5fd4a_14
    - clang 15.0.7 h694c41f_3
    - clang-15 15.0.7 default_hdb78580_3
    - clang_osx-arm64 15.0.7 h1cd4f45_3
    - clangxx 15.0.7 default_hdb78580_3
    - clangxx_osx-arm64 15.0.7 hc662a55_3
    - cmake 3.27.4 hf40c264_4
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - icu 73.2 hf5e326d_0
    - krb5 1.21.2 hb884880_0
    - ld64_osx-64 609 h0fd476b_14
    - ld64_osx-arm64 609 he51b688_14
    - libclang-cpp15 15.0.7 default_hdb78580_3
    - libcurl 8.3.0 h5f667d7_0
    - libcxx 16.0.6 hd57cbcb_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 haf1e3a3_1
    - libexpat 2.5.0 hf0c8a7f_1
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_3
    - libnghttp2 1.52.0 he2ab024_0
    - libssh2 1.11.0 hd019ec5_0
    - libuv 1.46.0 h0c2f820_0
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 15.0.7 he4b1e75_3
    - make 4.3 h22f3db7_1
    - ncurses 6.4 hf0c8a7f_0
    - openssl 3.1.2 h8a1eda9_0
    - rhash 1.4.4 h0dc2134_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - lerc 4.0.0 h9a09cb3_0
    - libcxx 16.0.6 h4653b0c_0
    - libdeflate 1.18 h1a8c8d9_0
    - libjpeg-turbo 2.1.5.1 hb547adb_1
    - libpng 1.6.39 h76d750c_0
    - libtiff 4.6.0 h23a1a89_0
    - libwebp-base 1.3.1 hb547adb_0
    - libzlib 1.2.13 h53f4e23_5
    - xz 5.2.6 h57fd34a_0
    - zlib 1.2.13 h53f4e23_5
    - zstd 1.5.5 h4f39d0f_0
  run:
    - libcxx >=15.0.7
    - libpng >=1.6.39,<1.7.0a0
    - libtiff >=4.6.0,<4.7.0a0
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - opj_dump -i p0_01.j2k
  files:
    - p0_01.j2k
about:
  home: http://www.openjpeg.org/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: An open-source JPEG 2000 codec written in C
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - gillins
    - mingwandroid
    - ocefpaf
