# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Tue Aug 15 11:02:21 2023
# ------------------------------------------------

package:
  name: krb5
  version: 1.21.2
source:
  sha256: 5827fa39ead0e7f7b8a158799eb5d50b194129e81b378892caedcafe50c5c195
  url: https://github.com/krb5/krb5/archive/krb5-1.21.2-final.tar.gz
build:
  missing_dso_whitelist:
    - /usr/lib/libresolv.9.dylib
  number: '0'
  run_exports:
    - krb5 >=1.21.2,<1.22.0a0
  string: h92f50d5_0
requirements:
  build:
    - autoconf 2.71 pl5321hed12c24_1
    - bison 3.8.2 hd7636e7_0
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 habff3f6_14
    - cctools_osx-arm64 973.0.1 h2f5fd4a_14
    - clang 15.0.7 h694c41f_3
    - clang-15 15.0.7 default_hdb78580_3
    - clang_osx-arm64 15.0.7 h1cd4f45_3
    - clangxx 15.0.7 default_hdb78580_3
    - clangxx_osx-arm64 15.0.7 hc662a55_3
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - flex 2.6.4 hcc69e7b_1004
    - gettext 0.21.1 h8a4c099_0
    - icu 72.1 h7336db1_0
    - ld64_osx-64 609 h0fd476b_14
    - ld64_osx-arm64 609 he51b688_14
    - libclang-cpp15 15.0.7 default_hdb78580_3
    - libcxx 16.0.6 hd57cbcb_0
    - libexpat 2.5.0 hf0c8a7f_1
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_3
    - libsqlite 3.42.0 h58db7d2_0
    - libtool 2.4.7 hf0c8a7f_0
    - libxml2 2.11.5 hd95e348_0
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 15.0.7 he4b1e75_3
    - m4 1.4.18 haf1e3a3_1001
    - make 4.3 h22f3db7_1
    - ncurses 6.4 hf0c8a7f_0
    - openssl 3.1.2 h8a1eda9_0
    - perl 5.32.1 4_h0dc2134_perl5
    - pkg-config 0.29.2 ha3d46e9_1008
    - python 3.11.4 h30d4d87_0_cpython
    - readline 8.2 h9e318b2_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2023c h71feb2d_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.2 h829000d_7
  host:
    - ca-certificates 2023.7.22 hf0a4a13_0
    - libcxx 16.0.6 h4653b0c_0
    - libedit 3.1.20191231 hc8eb9b7_2
    - ncurses 6.4 h7ea286d_0
    - openssl 3.1.2 h53f4e23_0
  run:
    - libcxx >=15.0.7
    - libedit >=3.1.20191231,<3.2.0a0
    - libedit >=3.1.20191231,<4.0a0
    - openssl >=3.1.2,<4.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libkrb5${SHLIB_EXT}
about:
  home: http://web.mit.edu/kerberos/
  license: MIT
  license_file: doc/notice.rst
  summary: A network authentication protocol.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - mariusvniekerk
    - mingwandroid
    - ocefpaf
    - pelson
    - wolfv
