# This file created by conda-build 3.24.0
# ------------------------------------------------

package:
  name: libzlib
  version: 1.2.13
source:
  sha256: b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30
  url:
    - http://zlib.net/zlib-1.2.13.tar.gz
    - https://gnupg.org/ftp/gcrypt/zlib/zlib-1.2.13.tar.gz
build:
  number: 5
  run_exports:
    - libzlib >=1.2.13,<1.3.0a0
  string: h53f4e23_5
requirements:
  build:
    - clang_bootstrap_osx-arm64 15.0.7 h84ec8a4_3
  run: []
  run_constrained:
    - zlib 1.2.13 *_5
test:
  commands:
    - test ! -f ${PREFIX}/lib/libz.a
    - test ! -f ${PREFIX}/lib/libz${SHLIB_EXT}
    - test ! -f ${PREFIX}/include/zlib.h
about:
  description: 'zlib is designed to be a free, general-purpose, lossless data-compression

    library for use on virtually any computer hardware and operating system.

    '
  dev_url: https://github.com/madler/zlib
  doc_url: http://zlib.net/manual.html
  home: http://zlib.net/
  license: Zlib
  license_family: Other
  license_file: license.txt
  summary: Massively spiffy yet delicately unobtrusive compression library
extra:
  copy_test_source_files: true
  feedstock-name: zlib
  final: true
  recipe-maintainers:
    - groutr
    - isuruf
    - msarahan
    - ocefpaf
