# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Mar 14 10:17:23 2023
# ------------------------------------------------

package:
  name: arviz
  version: 0.15.1
source:
  sha256: 981cce0282bdf6f3b379255b95a440979f9a0ef0ae9dd88a54f763cf5b31484c
  url: https://pypi.io/packages/source/a/arviz/arviz-0.15.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/arviz_1678789125032/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.12.7 ha878542_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.40.0 h753d276_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.8 h0b41bf4_0
    - pip 23.0.1 pyhd8ed1ab_0
    - python 3.11.0 he550d4f_1_cpython
    - readline 8.1.2 h0f457ee_0
    - setuptools 67.6.0 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tzdata 2022g h191b570_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - h5netcdf >=1.0.2
    - matplotlib-base >=3.5
    - numpy >=1.20
    - packaging
    - pandas >=1.4
    - python >=3
    - scipy >=1.8
    - setuptools >=60.0
    - typing_extensions >=4.1.0
    - xarray >=0.21.0
    - xarray-einstats >=0.3
test:
  commands:
    - pip check
  imports:
    - arviz
  requires:
    - pip
about:
  description: 'ArviZ (pronounced "AR-vees") is a Python package for exploratory analysis

    of Bayesian models. Includes functions for posterior analysis, model

    checking, comparison and diagnostics.

    '
  dev_url: https://github.com/arviz-devs/arviz
  doc_url: https://arviz-devs.github.io/arviz/index.html
  home: https://github.com/arviz-devs/arviz
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Exploratory analysis of Bayesian models with Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ColCarroll
    - OriolAbril
    - ahartikainen
    - aloctavodia
    - canyon289
    - ericmjl
