# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Sep 13 14:34:41 2023
# ------------------------------------------------

package:
  name: freetype
  version: 2.12.1
source:
  patches:
    - CVE-2022-37434.patch
  sha256: efe71fd4b8246f1b0b1b9bfca13cfff1c9ad85930340c27df469733bbb620938
  url: https://download.savannah.gnu.org/releases/freetype/freetype-2.12.1.tar.gz
build:
  number: '2'
  run_exports:
    - freetype >=2.12.1,<3.0a0
  string: hadb7bae_2
requirements:
  build:
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 habff3f6_14
    - cctools_osx-arm64 973.0.1 h2f5fd4a_14
    - clang 15.0.7 h694c41f_3
    - clang-15 15.0.7 default_hdb78580_3
    - clang_osx-arm64 15.0.7 h1cd4f45_3
    - clangxx 15.0.7 default_hdb78580_3
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 609 h0fd476b_14
    - ld64_osx-arm64 609 he51b688_14
    - libclang-cpp15 15.0.7 default_hdb78580_3
    - libcxx 16.0.6 hd57cbcb_0
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_3
    - libtool 2.4.7 hf0c8a7f_0
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 15.0.7 he4b1e75_3
    - make 4.3 h22f3db7_1
    - openssl 3.1.2 h8a1eda9_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - libpng 1.6.39 h76d750c_0
    - libzlib 1.2.13 h53f4e23_5
    - zlib 1.2.13 h53f4e23_5
  run:
    - libpng >=1.6.39,<1.7.0a0
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - ${PREFIX}/bin/freetype-config --version
about:
  description: 'FreeType is designed to be small, efficient, highly customizable

    and portable while capable of producing high-quality output (glyph images)

    of most vector and bitmap font formats.

    '
  dev_url: http://git.savannah.gnu.org/cgit/freetype/
  doc_source_url: https://sourceforge.net/projects/freetype/?source=navbar
  doc_url: http://freetype.sourceforge.net/freetype2/documentation.html
  home: https://www.freetype.org/
  license: GPL-2.0-only OR FTL
  license_file:
    - docs/FTL.TXT
    - docs/GPLv2.TXT
  summary: A Free, High-Quality, and Portable Font Engine
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ccordoba12
    - msarahan
    - ocefpaf
