# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sat Jul 16 13:14:05 2022
# ------------------------------------------------

package:
  name: lerc
  version: 4.0.0
source:
  sha256: 91431c2b16d0e3de6cbaea188603359f87caed08259a645fd5a3805784ee30a0
  url: https://github.com/Esri/lerc/archive/v4.0.0.tar.gz
build:
  number: '0'
  run_exports:
    - lerc >=4.0.0,<5.0a0
  string: h9a09cb3_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - c-ares 1.18.1 h0d85af4_0
    - ca-certificates 2022.6.15 h033912b_0
    - cctools_osx-64 973.0.1 h3eff9a4_10
    - cctools_osx-arm64 973.0.1 h98580c8_10
    - clang 13.0.1 h694c41f_0
    - clang-13 13.0.1 default_he082bbe_0
    - clang_osx-arm64 13.0.1 hdd0e76e_2
    - clangxx 13.0.1 default_he082bbe_0
    - clangxx_osx-arm64 13.0.1 hdeb254d_2
    - cmake 3.23.2 hf2c7296_0
    - compiler-rt 13.0.1 he01351e_0
    - compiler-rt_osx-64 13.0.1 hd3f61c9_0
    - expat 2.4.8 h96cf925_0
    - krb5 1.19.3 hb98e516_0
    - ld64_osx-64 609 h6fbe7a8_10
    - ld64_osx-arm64 609 hee039ab_10
    - libclang-cpp13 13.0.1 default_he082bbe_0
    - libcurl 7.83.1 h23f1065_0
    - libcxx 14.0.6 hce7ea42_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 haf1e3a3_1
    - libllvm13 13.0.1 h64f94b2_2
    - libllvm14 14.0.6 h41df66c_0
    - libnghttp2 1.47.0 hca56917_0
    - libssh2 1.10.0 hd3787cc_2
    - libuv 1.44.2 hac89ed1_0
    - libzlib 1.2.12 hfe4f2af_2
    - llvm-tools 13.0.1 h64f94b2_2
    - lz4-c 1.9.3 he49afe7_1
    - make 4.3 h22f3db7_1
    - ncurses 6.3 h96cf925_1
    - openssl 3.0.5 hfe4f2af_0
    - rhash 1.4.3 hac89ed1_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.12 hfe4f2af_2
    - zstd 1.5.2 ha9df2e0_2
  host:
    - libcxx 14.0.6 h04bba0f_0
  run:
    - libcxx >=13.0.1
test:
  commands:
    - test -f ${PREFIX}/lib/libLerc${SHLIB_EXT}
    - test -f ${PREFIX}/include/Lerc_types.h
about:
  description: 'LERC is an open-source image or raster format which

    supports rapid encoding and decoding for any pixel type

    (not just RGB or Byte). Users set the maximum compression

    error per pixel while encoding, so the precision of the

    original input image is preserved (within user defined

    error bounds).

    '
  home: https://github.com/Esri/lerc
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: LERC - Limited Error Raster Compression
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - hmaarrfk
