# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: matplotlib
  version: 3.8.0
source:
  sha256: 83e97200421dc8b0022eba92f03174d9bf80c966df25a6f03f44608bfe36a7ac
  url: https://github.com/matplotlib/matplotlib/archive/v3.8.0.tar.gz
build:
  number: 1
  string: py311ha1ab1f8_1
requirements:
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2023.7.22 hf0a4a13_0
    - libexpat 2.5.0 hb7217d7_1
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.43.0 hb31c410_0
    - libzlib 1.2.13 h53f4e23_5
    - ncurses 6.4 h7ea286d_0
    - openssl 3.1.3 h53f4e23_0
    - python 3.11.5 h47c9636_0_cpython
    - readline 8.2 h92ec313_1
    - tk 8.6.12 he1e0b03_0
    - tzdata 2023c h71feb2d_0
    - xz 5.2.6 h57fd34a_0
  run:
    - matplotlib-base >=3.8.0,<3.8.1.0a0
    - python >=3.11,<3.12.0a0
    - python_abi 3.11.* *_cp311
    - tornado >=5
test:
  imports:
    - matplotlib
about:
  description: 'matplotlib is a python 2D plotting library which produces publication

    quality figures in a variety of hardcopy formats and interactive

    environments across platforms. matplotlib can be used in Python scripts,

    the Python and IPython shell (ala MATLAB or Mathematica), web

    application servers, and six graphical user interface toolkits.

    '
  dev_url: https://github.com/matplotlib/matplotlib/
  doc_url: http://matplotlib.org/contents.html
  home: http://matplotlib.org/
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE/LICENSE
  license_url: http://matplotlib.sourceforge.net/users/license.html
  summary: Publication quality figures in Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - dopplershift
    - mdboom
    - ocefpaf
    - pelson
    - tacaswell
