# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Tue Nov 22 00:03:36 2022
# ------------------------------------------------

package:
  name: libpng
  version: 1.6.39
source:
  patches:
    - 0001-Include-pkg-config-files-in-the-Windows-packages-too.patch
    - 0002-Ensure-that-lm-is-not-included-in-Windows-pkg-config.patch
  sha256: af4fb7f260f839919e5958e5ab01a275d4fe436d45442a36ee62f73e5beb75ba
  url: http://download.sourceforge.net/libpng/libpng-1.6.39.tar.gz
build:
  number: '0'
  run_exports:
    - libpng >=1.6.39,<1.7.0a0
  string: h76d750c_0
requirements:
  build:
    - autoconf 2.69 pl5321hc0e15e3_11
    - automake 1.16.5 pl5321h694c41f_0
    - ca-certificates 2022.9.24 h033912b_0
    - cctools_osx-64 973.0.1 hcc6d90d_11
    - cctools_osx-arm64 973.0.1 hfd1dfa6_11
    - clang 14.0.6 h694c41f_0
    - clang-14 14.0.6 default_h55ffa42_0
    - clang_osx-arm64 14.0.6 he41d1a2_4
    - clangxx 14.0.6 default_h55ffa42_0
    - compiler-rt 14.0.6 h613da45_0
    - compiler-rt_osx-64 14.0.6 hab78ec2_0
    - ld64_osx-64 609 hfd63004_11
    - ld64_osx-arm64 609 h566df06_11
    - libclang-cpp14 14.0.6 default_h55ffa42_0
    - libcxx 14.0.6 hccf4f1f_0
    - libllvm14 14.0.6 h5b596cc_1
    - libtool 2.4.6 he49afe7_1008
    - libzlib 1.2.13 hfd90126_4
    - llvm-tools 14.0.6 h5b596cc_1
    - m4 1.4.18 haf1e3a3_1001
    - make 4.3 h22f3db7_1
    - openssl 3.0.7 hfd90126_0
    - perl 5.32.1 2_h0d85af4_perl5
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
  host:
    - libzlib 1.2.13 h03a7124_4
    - zlib 1.2.13 h03a7124_4
  run:
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libpng.a
    - test -f ${PREFIX}/lib/libpng${SHLIB_EXT}
    - libpng-config --version
about:
  description: 'libpng is the official PNG reference library. It supports almost all
    PNG

    features, is extensible, and has been extensively tested for over 20 years.

    '
  dev_url: https://sourceforge.net/p/libpng/code/ci/libpng16/tree/
  doc_url: http://www.libpng.org/pub/png/libpng.html
  home: http://www.libpng.org/pub/png/libpng.html
  license: zlib-acknowledgement
  license_file: LICENSE
  license_url: http://www.libpng.org/pub/png/src/libpng-LICENSE.txt
  summary: PNG reference library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - pkgw
