# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: llvm-openmp
  version: 17.0.2
source:
  folder: llvm-project
  sha256: 351562b14d42fcefcbf00cc1f327680a1062bbbf67a1e1ca6acb64c473b06394
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.2/llvm-project-17.0.2.src.tar.xz
build:
  ignore_run_exports:
    - _openmp_mutex
    - libgcc-ng
    - libstdcxx-ng
  number: 0
  run_exports:
    strong:
      - llvm-openmp >=17.0.2
  string: h1c12783_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - c-ares 1.19.1 h0dc2134_0
    - ca-certificates 2023.7.22 h8857fd0_0
    - clang_bootstrap_osx-arm64 15.0.7 h84ec8a4_3
    - cmake 3.27.6 hf40c264_0
    - krb5 1.21.2 hb884880_0
    - libcurl 8.3.0 h5f667d7_0
    - libcxx 16.0.6 hd57cbcb_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 haf1e3a3_1
    - libexpat 2.5.0 hf0c8a7f_1
    - libnghttp2 1.52.0 he2ab024_0
    - libssh2 1.11.0 hd019ec5_0
    - libuv 1.46.0 h0c2f820_0
    - libzlib 1.2.13 h8a1eda9_5
    - ncurses 6.4 hf0c8a7f_0
    - ninja 1.11.1 hb8565cd_0
    - openssl 3.1.3 h8a1eda9_0
    - perl 5.32.1 4_h0dc2134_perl5
    - rhash 1.4.4 h0dc2134_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - icu 73.2 hc8870d7_0
    - libcxx 16.0.6 h4653b0c_0
    - libiconv 1.17 he4db4b2_0
    - libllvm17 17.0.2 he79909e_0
    - libxml2 2.11.5 h25269f3_1
    - libzlib 1.2.13 h53f4e23_5
    - llvm-tools 17.0.2 he79909e_0
    - llvmdev 17.0.2 he79909e_0
    - xz 5.2.6 h57fd34a_0
    - zstd 1.5.5 h4f39d0f_0
  run: []
  run_constrained:
    - openmp 17.0.2|17.0.2.*
test:
  commands:
    - test -f $PREFIX/lib/libomp.dylib
    - test -f $PREFIX/include/omp.h
    - $PREFIX/bin/clang -v -fopenmp -I$PREFIX/include -L$PREFIX/lib -Wl,-rpath,$PREFIX/lib
      $LNK_XTRA omp_hello.c -o omp_hello
    - ./omp_hello
  files:
    - omp_hello.c
  requires:
    - clang_bootstrap_osx-arm64 15.*
    - clangxx
about:
  dev_url: https://github.com/llvm/llvm-project/
  home: http://openmp.llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_file: openmp/LICENSE.TXT
  summary: The OpenMP API supports multi-platform shared-memory parallel programming
    in C/C++ and Fortran.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - beckermr
    - h-vetinari
    - inducer
    - isuruf
    - jakirkham
    - katietz
    - yesimon
