# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: libopenblas
  version: 0.3.24
source:
  sha256: ceadc5065da97bd92404cac7254da66cc6eb192679cf1002098688978d4d5132
  url: https://github.com/xianyi/OpenBLAS/archive/v0.3.24.tar.gz
build:
  number: 0
  run_exports:
    - libopenblas >=0.3.24,<1.0a0
  string: openmp_hd76b1f2_0
  track_features: null
requirements:
  build:
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 habff3f6_14
    - cctools_osx-arm64 973.0.1 h2f5fd4a_14
    - clang 15.0.7 h694c41f_3
    - clang-15 15.0.7 default_hdb78580_3
    - clang_osx-arm64 15.0.7 h1cd4f45_3
    - clangxx 15.0.7 default_hdb78580_3
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - gfortran_impl_osx-64 12.3.0 h54fd467_1
    - gfortran_impl_osx-arm64 12.3.0 h73c6311_1
    - gfortran_osx-arm64 12.3.0 h64a2375_1
    - gmp 6.2.1 h2e338ed_0
    - icu 73.2 hf5e326d_0
    - isl 0.25 hb486fe8_0
    - ld64_osx-64 609 h0fd476b_14
    - ld64_osx-arm64 609 he51b688_14
    - libclang-cpp15 15.0.7 default_hdb78580_3
    - libcxx 16.0.6 hd57cbcb_0
    - libgfortran-devel_osx-64 12.3.0 h0b6f5ec_1
    - libgfortran-devel_osx-arm64 12.3.0 hc62be1c_1
    - libgfortran5 12.3.0 hbd3c1fe_1
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_3
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-openmp 15.0.7 h61d9ccf_0
    - llvm-tools 15.0.7 he4b1e75_3
    - mpc 1.3.1 h81bd1dd_0
    - mpfr 4.2.0 h4f9bd69_0
    - openssl 3.1.2 h8a1eda9_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zlib 1.2.13 h8a1eda9_5
    - zstd 1.5.5 h829000d_0
  host:
    - libgfortran 5.0.0 12_3_0_hd922786_1
    - libgfortran5 12.3.0 ha3a6a3e_1
    - llvm-openmp 16.0.6 h1c12783_0
  run:
    - libgfortran 5.*
    - libgfortran5 >=12.3.0
    - llvm-openmp >=15.0.7
  run_constrained:
    - openblas >=0.3.24,<0.3.25.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libopenblasp-r0.3.24.dylib
    - nm -g ${PREFIX}/lib/libopenblasp-r0.3.24.dylib | grep dsecnd
    - python -c "import ctypes; ctypes.cdll['${PREFIX}/lib/libopenblasp-r0.3.24.dylib']"
  requires:
    - python *
about:
  dev_url: https://github.com/xianyi/openblas
  home: http://www.openblas.net/
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - lapack-netlib/LICENSE
  summary: An optimized BLAS library based on GotoBLAS2 1.13 BSD version
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - gillins
    - groutr
    - h-vetinari
    - isuruf
    - jakirkham
