# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Sep 25 17:01:10 2023
# ------------------------------------------------

package:
  name: libtiff
  version: 4.6.0
source:
  patches:
    - patches/use_unix_io.patch
  sha256: 88b3979e6d5c7e32b50d7ec72fb15af724f6ab2cbf7e10880c360a77e4b5d99a
  url: https://download.osgeo.org/libtiff/tiff-4.6.0.tar.gz
build:
  missing_dso_whitelist:
    - /opt/X11/lib/libGL.1.dylib
    - /opt/X11/lib/libglut.3.dylib
  number: '2'
  run_exports:
    - libtiff >=4.6.0,<4.7.0a0
  string: ha8a6c65_2
requirements:
  build:
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 habff3f6_14
    - cctools_osx-arm64 973.0.1 h2f5fd4a_14
    - clang 15.0.7 h694c41f_3
    - clang-15 15.0.7 default_hdb78580_3
    - clang_osx-arm64 15.0.7 h1cd4f45_3
    - clangxx 15.0.7 default_hdb78580_3
    - clangxx_osx-arm64 15.0.7 hc662a55_3
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 609 h0fd476b_14
    - ld64_osx-arm64 609 he51b688_14
    - libclang-cpp15 15.0.7 default_hdb78580_3
    - libcxx 16.0.6 hd57cbcb_0
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_3
    - libtool 2.4.7 hf0c8a7f_0
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 15.0.7 he4b1e75_3
    - make 4.3 h22f3db7_1
    - openssl 3.1.3 h8a1eda9_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - lerc 4.0.0 h9a09cb3_0
    - libcxx 16.0.6 h4653b0c_0
    - libdeflate 1.19 hb547adb_0
    - libjpeg-turbo 3.0.0 hb547adb_1
    - libwebp-base 1.3.2 hb547adb_0
    - libzlib 1.2.13 h53f4e23_5
    - xz 5.2.6 h57fd34a_0
    - zlib 1.2.13 h53f4e23_5
    - zstd 1.5.5 h4f39d0f_0
  run:
    - lerc >=4.0.0,<5.0a0
    - libcxx >=15.0.7
    - libdeflate >=1.19,<1.20.0a0
    - libjpeg-turbo >=3.0.0,<4.0a0
    - libwebp-base >=1.3.2,<2.0a0
    - libzlib >=1.2.13,<1.3.0a0
    - xz >=5.2.6,<6.0a0
    - zstd >=1.5.5,<1.6.0a0
test:
  commands:
    - test ! -f ${PREFIX}/lib/libtiff.a
    - test ! -f ${PREFIX}/lib/libtiffxx.a
    - test -f ${PREFIX}/lib/libtiff.dylib
    - test -f ${PREFIX}/lib/libtiffxx.dylib
about:
  description: 'This software provides support for the Tag Image File Format (TIFF),
    a

    widely used format for storing image data.

    '
  doc_url: http://www.libtiff.org/document.html
  home: http://www.libtiff.org/
  license: HPND
  license_file: LICENSE.md
  summary: Support for the Tag Image File Format (TIFF).
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - hmaarrfk
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - stuarteberg
