# This file created by conda-build 3.24.0
# ------------------------------------------------

package:
  name: libexpat
  version: 2.5.0
source:
  sha256: 6f0e6e01f7b30025fa05c85fdad1e5d0ec7fd35d9f61b22f34998de11969ff67
  url: https://github.com/libexpat/libexpat/releases/download/R_2_5_0/expat-2.5.0.tar.bz2
build:
  ignore_run_exports_from:
    - clangxx_osx-arm64 14.*
  number: 1
  string: hb7217d7_1
requirements:
  build:
    - ca-certificates 2022.12.7 h033912b_0
    - cctools_osx-64 973.0.1 hcc6d90d_13
    - cctools_osx-arm64 973.0.1 hfd1dfa6_13
    - clang 14.0.6 h694c41f_0
    - clang-14 14.0.6 default_h55ffa42_0
    - clang_osx-arm64 14.0.6 he41d1a2_6
    - clangxx 14.0.6 default_h55ffa42_0
    - clangxx_osx-arm64 14.0.6 h748fd88_6
    - compiler-rt 14.0.6 h613da45_0
    - compiler-rt_osx-64 14.0.6 hab78ec2_0
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - ld64_osx-64 609 hfd63004_13
    - ld64_osx-arm64 609 h566df06_13
    - libclang-cpp14 14.0.6 default_h55ffa42_0
    - libcxx 16.0.0 h71dddab_0
    - libllvm14 14.0.6 h5b596cc_1
    - libzlib 1.2.13 hfd90126_4
    - llvm-tools 14.0.6 h5b596cc_1
    - make 4.3 h22f3db7_1
    - openssl 3.1.0 hfd90126_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
  run: []
  run_constrained:
    - expat 2.5.0.*
test: {}
about:
  home: http://expat.sourceforge.net/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Expat XML parser library in C
extra:
  copy_test_source_files: true
  feedstock-name: expat
  final: true
  recipe-maintainers:
    - isuruf
    - kwilcox
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
