# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Jan  8 02:05:37 2021
# ------------------------------------------------

package:
    name: xorg-libxdmcp
    version: 1.1.3
source:
    fn: xorg-libXdmcp-1.1.3.tar.bz2
    patches: null
    sha256: 20523b44aaa513e17c009e873ad7bbc301507a3224c232610ce2e099011c6529
    url: https://www.x.org/releases/individual/lib/libXdmcp-1.1.3.tar.bz2
build:
    detect_binary_files_with_prefix: true
    number: '0'
    string: h27ca646_0
requirements:
    build:
        - autoconf 2.69 pl5320hbcb3906_10
        - automake 1.16.2 pl5320h694c41f_3
        - cctools_osx-arm64 949.0.1 h9541561_19
        - clang 11.0.0 h694c41f_2
        - clang-11 11.0.0 default_h9e6edd0_2
        - clang_osx-arm64 11.0.0 h40be2b1_8
        - clangxx 11.0.0 default_h9e6edd0_2
        - compiler-rt 11.0.0 h01488ec_2
        - compiler-rt_osx-64 11.0.0 hd3c4e95_2
        - gettext 0.19.8.1 h7937167_1005
        - gnuconfig 2020.11.07 hd8ed1ab_0
        - ld64_osx-64 530 hea264c1_19
        - ld64_osx-arm64 530 ha0a8365_19
        - ldid 2.1.2 h7660a38_2
        - libclang-cpp11 11.0.0 default_h9e6edd0_2
        - libcxx 11.0.0 h4c3b8ed_1
        - libffi 3.3 h046ec9c_2
        - libiconv 1.16 haf1e3a3_0
        - libllvm11 11.0.0 hf85e3d2_0
        - libtool 2.4.6 h2e338ed_1007
        - llvm-tools 11.0.0 hf85e3d2_0
        - m4 1.4.18 haf1e3a3_1001
        - make 4.3 h22f3db7_1
        - perl 5.32.0 hbcb3906_0
        - pkg-config 0.29.2 h31203cd_1008
        - tapi 1100.0.11 h9ce4665_0
        - zlib 1.2.11 h7795811_1010
    host:
        - xorg-util-macros 1.19.2 h27ca646_1001
        - xorg-xproto 7.0.31 h27ca646_1007
    run: []
test:
    commands:
        - test -f $PREFIX/lib/libXdmcp.dylib
about:
    home: https://www.x.org/
    license: MIT
    license_family: MIT
    license_file: COPYING
    summary: The X-windows display manager client protocol library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pkgw
