# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Thu Sep 14 16:26:23 2023
# ------------------------------------------------

package:
  name: libwebp-base
  version: 1.3.2
source:
  sha256: 2a499607df669e40258e53d0ade8035ba4ec0175244869d1025d460562aa09b4
  url: http://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.3.2.tar.gz
build:
  number: '0'
  run_exports:
    - libwebp-base >=1.3.2,<2.0a0
  string: hb547adb_0
requirements:
  build:
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 habff3f6_14
    - cctools_osx-arm64 973.0.1 h2f5fd4a_14
    - clang 15.0.7 h694c41f_3
    - clang-15 15.0.7 default_hdb78580_3
    - clang_osx-arm64 15.0.7 h1cd4f45_3
    - clangxx 15.0.7 default_hdb78580_3
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 609 h0fd476b_14
    - ld64_osx-arm64 609 he51b688_14
    - libclang-cpp15 15.0.7 default_hdb78580_3
    - libcxx 16.0.6 hd57cbcb_0
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_3
    - libtool 2.4.7 hf0c8a7f_0
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 15.0.7 he4b1e75_3
    - make 4.3 h22f3db7_1
    - openssl 3.1.2 h8a1eda9_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  run: []
  run_constrained:
    - libwebp 1.3.2
test:
  commands:
    - test -f $PREFIX/lib/libwebp.dylib
    - test ! -f $PREFIX/lib/libwebp.a
    - test $PREFIX/pkgconfig/libwebp.pc
    - test -f $PREFIX/lib/libwebpdemux.dylib
    - test ! -f $PREFIX/lib/libwebpdemux.a
    - test $PREFIX/pkgconfig/libwebpdemux.pc
    - test -f $PREFIX/lib/libwebpmux.dylib
    - test ! -f $PREFIX/lib/libwebpmux.a
    - test $PREFIX/pkgconfig/libwebpmux.pc
    - test -f $PREFIX/lib/libwebpdecoder.dylib
    - test ! -f $PREFIX/lib/libwebpdecoder.a
    - test $PREFIX/pkgconfig/libwebpdecoder.pc
    - test -f $PREFIX/lib/libsharpyuv.dylib
    - test ! -f $PREFIX/lib/libsharpyuv.a
    - test $PREFIX/pkgconfig/libsharpyuv.pc
    - test -f $PREFIX/include/webp/decode.h || (echo "decode.h not found" && exit
      1)
    - test -f $PREFIX/include/webp/demux.h || (echo "demux.h not found" && exit 1)
    - test -f $PREFIX/include/webp/encode.h || (echo "encode.h not found" && exit
      1)
    - test -f $PREFIX/include/webp/mux_types.h || (echo "mux_types.h not found" &&
      exit 1)
    - test -f $PREFIX/include/webp/mux.h || (echo "mux.h not found" && exit 1)
    - test -f $PREFIX/include/webp/types.h || (echo "types.h not found" && exit 1)
    - test ! -f $PREFIX/bin/cwebp
    - test ! -f $PREFIX/bin/dwebp
    - test ! -f $PREFIX/bin/gif2webp
    - test ! -f $PREFIX/bin/img2webp
    - test ! -f $PREFIX/bin/webpinfo
    - test ! -f $PREFIX/bin/webpmux
about:
  description: 'WebP is a method of lossy and lossless compression that can be used
    on a large variety of photographic, translucent and graphical images found on
    the web. The degree of lossy compression is adjustable so a user can choose the
    trade-off between file size and image quality. libwebp-base provides the headers
    and shared libraries. For cwebp and dwep, binaries install libwebp.

    '
  dev_url: https://chromium.googlesource.com/webm/libwebp
  doc_url: https://developers.google.com/speed/webp/docs/using
  home: https://developers.google.com/speed/webp
  license: BSD-3-Clause
  license_file: COPYING
  summary: WebP image library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - carterbox
    - dschreij
    - ocefpaf
