# This file created by conda-build 3.24.0
# ------------------------------------------------

package:
  name: libssh2
  version: 1.11.0
source:
  sha256: 3736161e41e2693324deb38c26cfdc3efe6209d634ba4258db1cecff6a5ad461
  url: https://www.libssh2.org/download/libssh2-1.11.0.tar.gz
build:
  number: 0
  run_exports:
    - libssh2 >=1.11.0,<2.0a0
  string: h7a5bd25_0
requirements:
  build:
    - ca-certificates 2023.5.7 h8857fd0_0
    - cctools_osx-arm64 973.0.1 he4d8a77_13
    - clang_bootstrap_osx-arm64 11.1.0 h169cfcd_7
    - cmake-no-system 3.18.0 hf0c8a7f_0
    - icu 72.1 h7336db1_0
    - ld64_osx-arm64 609 h59acfe3_13
    - libcxx 16.0.5 hd57cbcb_0
    - libiconv 1.17 hac89ed1_0
    - libllvm16 16.0.5 he4b1e75_0
    - libxml2 2.11.4 hd95e348_0
    - libzlib 1.2.13 hfd90126_4
    - make 4.3 h22f3db7_1
    - openssl 3.1.1 h8a1eda9_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.2 hbc0c0cd_6
  host:
    - ca-certificates 2023.5.7 hf0a4a13_0
    - libzlib 1.2.13 h03a7124_4
    - openssl 3.1.1 h53f4e23_1
    - zlib 1.2.13 h03a7124_4
  run:
    - libzlib >=1.2.13,<1.3.0a0
    - openssl >=3.1.1,<4.0a0
test:
  commands:
    - test -f $PREFIX/include/libssh2.h
    - test -f $PREFIX/include/libssh2_publickey.h
    - test -f $PREFIX/include/libssh2_sftp.h
    - test ! -f $PREFIX/lib/libssh2.a
    - test -f $PREFIX/lib/libssh2${SHLIB_EXT}
about:
  description: 'libssh2 is a library implementing the SSH2 protocol, available under
    the revised BSD license.

    '
  dev_url: https://github.com/libssh2/libssh2
  home: https://www.libssh2.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: the SSH library
extra:
  copy_test_source_files: true
  feedstock-name: libssh2
  final: true
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
    - shadowwalkersb
    - xhochy
