# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: scipy
  version: 1.11.3
source:
  - patches:
      - patches/0001-remove-comment-that-breaks-parsing.patch
    sha256: 86712f1dff2cf674d823ad5489db54928b44149f76d7ba891ad19a6ae118abcf
    url: https://github.com/scipy/scipy/archive/refs/tags/v1.11.3.tar.gz
  - folder: scipy/_lib/boost_math
    git_rev: 298a243ccd3639b6eaa59bcdab7ab9d5f008fb36
    git_url: https://github.com/boostorg/math.git
  - folder: scipy/_lib/highs
    git_rev: 4a122958a82e67e725d08153e099efe4dad099a2
    git_url: https://github.com/scipy/highs.git
  - folder: scipy/_lib/unuran
    git_rev: 81a1fd118b326880e00cc7d8989fb063782a6bdd
    git_url: https://github.com/scipy/unuran.git
  - folder: scipy/sparse/linalg/_propack/PROPACK
    git_rev: 96f6800451372dd003e627bbfd732937ac0c685e
    git_url: https://github.com/scipy/PROPACK.git
build:
  noarch: false
  noarch_python: false
  number: '1'
  script: build-output.sh
  string: py311h93d07a4_1
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 habff3f6_14
    - cctools_osx-arm64 973.0.1 h2f5fd4a_14
    - clang 15.0.7 h694c41f_3
    - clang-15 15.0.7 default_hdb78580_3
    - clang_osx-arm64 15.0.7 h1cd4f45_3
    - clangxx 15.0.7 default_hdb78580_3
    - clangxx_osx-arm64 15.0.7 hc662a55_3
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - cross-python_osx-arm64 3.11 41_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - gettext 0.21.1 h8a4c099_0
    - gfortran_impl_osx-64 13.2.0 h7643cbd_1
    - gfortran_impl_osx-arm64 12.3.0 h73c6311_1
    - gfortran_osx-arm64 12.3.0 h64a2375_1
    - gmp 6.2.1 h2e338ed_0
    - icu 73.2 hf5e326d_0
    - isl 0.25 hb486fe8_0
    - ld64_osx-64 609 h0fd476b_14
    - ld64_osx-arm64 609 he51b688_14
    - libclang-cpp15 15.0.7 default_hdb78580_3
    - libcxx 16.0.6 hd57cbcb_0
    - libexpat 2.5.0 hf0c8a7f_1
    - libffi 3.4.2 h0d85af4_5
    - libgfortran-devel_osx-64 13.2.0 h80d4556_1
    - libgfortran-devel_osx-arm64 12.3.0 hc62be1c_1
    - libgfortran5 13.2.0 h2873a65_1
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_3
    - libsqlite 3.43.0 h58db7d2_0
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-openmp 16.0.6 hff08bdf_0
    - llvm-tools 15.0.7 he4b1e75_3
    - lz4-c 1.9.4 hf0c8a7f_0
    - mpc 1.3.1 h81bd1dd_0
    - mpfr 4.2.0 h4f9bd69_0
    - ncurses 6.4 hf0c8a7f_0
    - openssl 3.1.3 h8a1eda9_0
    - popt 1.16 h7b079dc_2002
    - python 3.11.6 h30d4d87_0_cpython
    - readline 8.2 h9e318b2_1
    - rsync 3.2.7 h30d983d_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.13 hef22860_0
    - tzdata 2023c h71feb2d_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.6 h775f41a_0
    - zlib 1.2.13 h8a1eda9_5
    - zstd 1.5.5 h829000d_0
  host:
    - beniget 0.4.1 pyhd8ed1ab_0
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2023.7.22 hf0a4a13_0
    - cctools_osx-arm64 973.0.1 h62378fb_14
    - clang 16.0.6 he79909e_1
    - clang-16 16.0.6 default_h07b2d96_1
    - clang_osx-arm64 16.0.6 hc421ffc_1
    - clangxx 16.0.6 default_h298e243_1
    - clangxx_osx-arm64 16.0.6 hcd7bac0_1
    - colorama 0.4.6 pyhd8ed1ab_0
    - compiler-rt 16.0.6 hf8d1dfb_0
    - compiler-rt_osx-arm64 16.0.6 hf8d1dfb_0
    - cython 3.0.2 py311ha891d26_2
    - decorator 5.1.1 pyhd8ed1ab_0
    - gast 0.5.4 pyhd8ed1ab_0
    - gettext 0.21.1 h0186832_0
    - icu 73.2 hc8870d7_0
    - importlib-metadata 6.8.0 pyha770c72_0
    - ld64_osx-arm64 609 ha4bd21c_14
    - libblas 3.9.0 5_h880f123_netlib
    - libcblas 3.9.0 5_h880f123_netlib
    - libclang-cpp16 16.0.6 default_h07b2d96_1
    - libcxx 16.0.6 h4653b0c_0
    - libexpat 2.5.0 hb7217d7_1
    - libffi 3.4.2 h3422bc3_5
    - libgfortran 5.0.0 13_2_0_hd922786_1
    - libgfortran5 13.2.0 hf226fd6_1
    - libglib 2.78.0 h24e9cb9_0
    - libiconv 1.17 he4db4b2_0
    - liblapack 3.9.0 5_h880f123_netlib
    - libllvm16 16.0.6 he79909e_2
    - libsqlite 3.43.0 hb31c410_0
    - libxml2 2.11.5 h25269f3_1
    - libzlib 1.2.13 h53f4e23_5
    - llvm-openmp 16.0.6 h1c12783_0
    - llvm-tools 16.0.6 he79909e_2
    - meson 1.2.2 pyhd8ed1ab_0
    - meson-python 0.14.0 pyh0c530f3_0
    - ncurses 6.4 h7ea286d_0
    - ninja 1.11.1 hffc8910_0
    - numpy 1.23.5 py311ha92fb03_0
    - openssl 3.1.3 h53f4e23_0
    - packaging 23.2 pyhd8ed1ab_0
    - pcre2 10.40 hb34f9b4_0
    - pip 23.2.1 pyhd8ed1ab_0
    - pkg-config 0.29.2 hab62308_1008
    - ply 3.11 py_1
    - pybind11 2.11.1 py311he4fd1f5_2
    - pybind11-global 2.11.1 py311he4fd1f5_2
    - pyproject-metadata 0.7.1 pyhd8ed1ab_0
    - pyproject_hooks 1.0.0 pyhd8ed1ab_0
    - python 3.11.6 h47c9636_0_cpython
    - python-build 1.0.3 pyhd8ed1ab_0
    - python_abi 3.11 4_cp311
    - pythran 0.14.0 py311hddbb800_1
    - readline 8.2 h92ec313_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - sigtool 0.1.3 h44b9a77_0
    - tapi 1100.0.11 he4954df_0
    - tk 8.6.13 hb31c410_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.2 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
    - zipp 3.17.0 pyhd8ed1ab_0
    - zstd 1.5.5 h4f39d0f_0
  run:
    - libblas >=3.9.0,<4.0a0
    - libcblas >=3.9.0,<4.0a0
    - libcxx >=15.0.7
    - libgfortran 5.*
    - libgfortran5 >=12.3.0
    - libgfortran5 >=13.2.0
    - liblapack >=3.9.0,<4.0a0
    - numpy >=1.23.5,<1.28
    - numpy >=1.23.5,<2.0a0
    - python >=3.11,<3.12.0a0
    - python >=3.11,<3.12.0a0 *_cpython
    - python_abi 3.11.* *_cp311
test:
  commands:
    - test ! -d $SP_DIR/scipy/_lib/tests
    - test ! -d $SP_DIR/scipy/cluster/tests
    - test ! -d $SP_DIR/scipy/constants/tests
    - test ! -d $SP_DIR/scipy/datasets/tests
    - test ! -d $SP_DIR/scipy/fftpack/tests
    - test ! -d $SP_DIR/scipy/fft/tests
    - test ! -d $SP_DIR/scipy/integrate/tests
    - test ! -d $SP_DIR/scipy/interpolate/tests
    - test ! -d $SP_DIR/scipy/io/tests
    - test ! -d $SP_DIR/scipy/linalg/tests
    - test ! -d $SP_DIR/scipy/misc/tests
    - test ! -d $SP_DIR/scipy/ndimage/tests
    - test ! -d $SP_DIR/scipy/odr/tests
    - test ! -d $SP_DIR/scipy/optimize/tests
    - test ! -d $SP_DIR/scipy/signal/tests
    - test ! -d $SP_DIR/scipy/sparse/tests
    - test ! -d $SP_DIR/scipy/spatial/tests
    - test ! -d $SP_DIR/scipy/special/tests
    - test ! -d $SP_DIR/scipy/stats/tests
    - test ! -f $SP_DIR/scipy/_lib/_test_ccallback.cpython-311-darwin.so
    - test ! -f $SP_DIR/scipy/integrate/_test_multivariate.cpython-311-darwin.so
    - test ! -f $SP_DIR/scipy/io/_test_fortran.cpython-311-darwin.so
    - test ! -f $SP_DIR/scipy/ndimage/_ctest.cpython-311-darwin.so
    - test ! -f $SP_DIR/scipy/ndimage/_cytest.cpython-311-darwin.so
    - test ! -f $SP_DIR/scipy/special/_test_internal.cpython-311-darwin.so
    - python -c "import scipy; throw_away_the_return_value = scipy.test()" > testlog
    - python -c "import sys; lines=open('testlog').readlines(); sys.exit(0 if any('conda-forge
      builds of' in x for x in lines) else 1)"
    - (pytest --pyargs scipy || echo "failure was expected") > testlog
    - python -c "import sys; lines=open('testlog').readlines(); sys.exit(0 if any('conda-forge
      builds of' in x for x in lines) else 1)"
    - python -c "import sys; lines=open('testlog').readlines(); sys.exit(0 if any('========
      1 failed in ' in x for x in lines) else 1)"
  imports:
    - scipy
    - scipy.cluster
    - scipy.cluster.hierarchy
    - scipy.cluster.vq
    - scipy.constants
    - scipy.datasets
    - scipy.fft
    - scipy.fftpack
    - scipy.integrate
    - scipy.interpolate
    - scipy.io
    - scipy.io.arff
    - scipy.io.matlab
    - scipy.io.wavfile
    - scipy.linalg
    - scipy.linalg.blas
    - scipy.linalg.cython_blas
    - scipy.linalg.cython_lapack
    - scipy.linalg.interpolative
    - scipy.linalg.lapack
    - scipy.misc
    - scipy.ndimage
    - scipy.odr
    - scipy.optimize
    - scipy.signal
    - scipy.signal.windows
    - scipy.sparse
    - scipy.sparse.csgraph
    - scipy.sparse.linalg
    - scipy.spatial
    - scipy.spatial.distance
    - scipy.spatial.transform
    - scipy.special
    - scipy.stats
    - scipy.stats.contingency
    - scipy.stats.distributions
    - scipy.stats.mstats
    - scipy.stats.qmc
    - scipy.stats.sampling
  requires:
    - pytest
about:
  description: 'SciPy is a Python-based ecosystem of open-source software for mathematics,

    science, and engineering.

    '
  dev_url: https://github.com/scipy/scipy
  doc_url: http://www.scipy.org/docs.html
  home: http://www.scipy.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Scientific Library for Python
extra:
  copy_test_source_files: true
  feedstock-name: scipy
  final: true
  recipe-maintainers:
    - h-vetinari
    - jakirkham
    - msarahan
    - ocefpaf
    - rgommers
