# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Sep 29 06:36:31 2023
# ------------------------------------------------

package:
  name: lcms2
  version: '2.15'
source:
  patches:
    - win_jpegturbo.patch
  sha256: b20cbcbd0f503433be2a4e81462106fa61050a35074dc24a4e356792d971ab39
  url: https://github.com/mm2/Little-CMS/releases/download/lcms2.15/lcms2-2.15.tar.gz
build:
  number: '3'
  run_exports:
    - lcms2 >=2.15,<3.0a0
  string: hf2736f0_3
requirements:
  build:
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 habff3f6_14
    - cctools_osx-arm64 973.0.1 h2f5fd4a_14
    - clang 15.0.7 h694c41f_3
    - clang-15 15.0.7 default_hdb78580_3
    - clang_osx-arm64 15.0.7 h1cd4f45_3
    - clangxx 15.0.7 default_hdb78580_3
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 609 h0fd476b_14
    - ld64_osx-arm64 609 he51b688_14
    - libclang-cpp15 15.0.7 default_hdb78580_3
    - libcxx 16.0.6 hd57cbcb_0
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_3
    - libtool 2.4.7 hf0c8a7f_0
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 15.0.7 he4b1e75_3
    - make 4.3 h22f3db7_1
    - openssl 3.1.3 h8a1eda9_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - lerc 4.0.0 h9a09cb3_0
    - libcxx 16.0.6 h4653b0c_0
    - libdeflate 1.19 hb547adb_0
    - libjpeg-turbo 3.0.0 hb547adb_1
    - libtiff 4.6.0 ha8a6c65_2
    - libwebp-base 1.3.2 hb547adb_0
    - libzlib 1.2.13 h53f4e23_5
    - xz 5.2.6 h57fd34a_0
    - zstd 1.5.5 h4f39d0f_0
  run:
    - libjpeg-turbo >=3.0.0,<4.0a0
    - libtiff >=4.6.0,<4.7.0a0
test:
  commands:
    - test -f ${PREFIX}/include/lcms2.h
    - test ! -f ${PREFIX}/lib/liblcms2.a
    - test -f ${PREFIX}/lib/liblcms2${SHLIB_EXT}
    - jpgicc
    - tificc
    - linkicc
    - transicc
    - psicc
about:
  home: http://www.littlecms.com/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Open Source Color Management Engine
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - hmaarrfk
    - isuruf
