# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: zstd
  version: 1.5.5
source:
  patches: null
  sha256: 98e9c3d949d1b924e28e01eccb7deed865eefebf25c2f21c702e5cd5b63b85e1
  url: https://github.com/facebook/zstd/archive/v1.5.5.tar.gz
build:
  number: 0
  run_exports:
    - zstd >=1.5.5,<1.6.0a0
  string: h4f39d0f_0
requirements:
  build:
    - clang_bootstrap_osx-arm64 15.0.7 h84ec8a4_3
    - cmake-no-system 3.27.4 he965462_0
    - libcxx 16.0.6 hd57cbcb_0
    - make 4.3 h22f3db7_1
    - ninja 1.11.1 hb8565cd_0
  host:
    - libzlib 1.2.13 h53f4e23_5
    - zlib 1.2.13 h53f4e23_5
  run:
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libzstd.dylib
    - test ! -f ${PREFIX}/lib/libzstd.a
    - test -f ${PREFIX}/include/zstd.h
    - zstd -be -i5
    - test -f ${PREFIX}/lib/pkgconfig/libzstd.pc
    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
    - pkg-config --cflags libzstd
    - cd cf_test
  files:
    - cf_test/
  requires:
    - clang_bootstrap_osx-arm64 15.*
    - cmake
    - pkg-config
about:
  description: 'Zstandard is a real-time compression algorithm, providing high compression

    ratios. It offers a very wide range of compression / speed trade-off, while

    being backed by a very fast decoder. It also offers a special mode for

    small data, called dictionary compression, and can create dictionaries from

    any sample set. Zstandard library is provided as open source software using

    a BSD license.

    '
  dev_url: https://github.com/facebook/zstd
  doc_url: https://facebook.github.io/zstd/zstd_manual.html
  home: http://www.zstd.net
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Zstandard - Fast real-time compression algorithm
extra:
  copy_test_source_files: true
  feedstock-name: zstd
  final: true
  recipe-maintainers:
    - hmaarrfk
    - msarahan
    - rmax
    - xhochy
