# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Jul 30 17:23:02 2023
# ------------------------------------------------

package:
  name: pyparsing
  version: 3.1.1
source:
  sha256: ede28a1a32462f5a9705e07aea48001a08f7cf81a021585011deba701581a0db
  url: https://pypi.io/packages/source/p/pyparsing/pyparsing-3.1.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/pyparsing_1690737849915/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2023.7.22 hbcca054_0
    - flit-core 3.9.0 pyhd8ed1ab_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.1.0 he5830b7_0
    - libgomp 13.1.0 he5830b7_0
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.42.0 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.1 hd590300_1
    - pip 23.2.1 pyhd8ed1ab_0
    - python 3.11.4 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 68.0.0 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.6
test:
  commands:
    - pip check
  imports:
    - pyparsing
  requires:
    - pip
about:
  description: 'The pyparsing module is an alternative approach to creating and executing

    simple grammars, vs. the traditional lex/yacc approach, or the use of

    regular expressions. The pyparsing module provides a library of classes

    that client code uses to construct the grammar directly in Python code.

    '
  dev_url: https://svn.code.sf.net/p/pyparsing/code/
  doc_url: http://pyparsing.wikispaces.com/Documentation
  home: http://pyparsing.wikispaces.com/
  license: MIT
  license_file: LICENSE
  summary: Create and execute simple grammars
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jan-janssen
    - msarahan
    - ocefpaf
    - thewchan
