# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: matplotlib-base
  version: 3.8.0
source:
  sha256: 83e97200421dc8b0022eba92f03174d9bf80c966df25a6f03f44608bfe36a7ac
  url: https://github.com/matplotlib/matplotlib/archive/v3.8.0.tar.gz
build:
  ignore_run_exports_from:
    - zlib
  number: 1
  string: py311h3bc9839_1
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 habff3f6_14
    - cctools_osx-arm64 973.0.1 h2f5fd4a_14
    - clang 15.0.7 h694c41f_3
    - clang-15 15.0.7 default_hdb78580_3
    - clang_osx-arm64 15.0.7 h1cd4f45_3
    - clangxx 15.0.7 default_hdb78580_3
    - clangxx_osx-arm64 15.0.7 hc662a55_3
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - cross-python_osx-arm64 3.11 41_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - gettext 0.21.1 h8a4c099_0
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 609 h0fd476b_14
    - ld64_osx-arm64 609 he51b688_14
    - libblas 3.9.0 18_osx64_openblas
    - libcblas 3.9.0 18_osx64_openblas
    - libclang-cpp15 15.0.7 default_hdb78580_3
    - libcxx 16.0.6 hd57cbcb_0
    - libexpat 2.5.0 hf0c8a7f_1
    - libffi 3.4.2 h0d85af4_5
    - libgfortran 5.0.0 13_2_0_h97931a8_1
    - libgfortran5 13.2.0 h2873a65_1
    - libiconv 1.17 hac89ed1_0
    - liblapack 3.9.0 18_osx64_openblas
    - libllvm15 15.0.7 he4b1e75_3
    - libopenblas 0.3.24 openmp_h48a4ad5_0
    - libsqlite 3.43.0 h58db7d2_0
    - libtool 2.4.7 hf0c8a7f_0
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-openmp 16.0.6 hff08bdf_0
    - llvm-tools 15.0.7 he4b1e75_3
    - lz4-c 1.9.4 hf0c8a7f_0
    - ncurses 6.4 hf0c8a7f_0
    - numpy 1.23.5 py311h62c7003_0
    - openssl 3.1.3 h8a1eda9_0
    - pkg-config 0.29.2 ha3d46e9_1008
    - popt 1.16 h7b079dc_2002
    - pybind11 2.11.1 py311h5fe6e05_1
    - pybind11-global 2.11.1 py311h5fe6e05_1
    - python 3.11.5 h30d4d87_0_cpython
    - python_abi 3.11 4_cp311
    - readline 8.2 h9e318b2_1
    - rsync 3.2.7 h30d983d_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2023c h71feb2d_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2023.7.22 hf0a4a13_0
    - certifi 2023.7.22 pyhd8ed1ab_0
    - freetype 2.12.1 hadb7bae_2
    - libblas 3.9.0 18_osxarm64_openblas
    - libcblas 3.9.0 18_osxarm64_openblas
    - libcxx 16.0.6 h4653b0c_0
    - libexpat 2.5.0 hb7217d7_1
    - libffi 3.4.2 h3422bc3_5
    - libgfortran 5.0.0 13_2_0_hd922786_1
    - libgfortran5 13.2.0 hf226fd6_1
    - liblapack 3.9.0 18_osxarm64_openblas
    - libopenblas 0.3.24 openmp_hd76b1f2_0
    - libpng 1.6.39 h76d750c_0
    - libsqlite 3.43.0 hb31c410_0
    - libzlib 1.2.13 h53f4e23_5
    - llvm-openmp 16.0.6 h1c12783_0
    - ncurses 6.4 h7ea286d_0
    - numpy 1.23.5 py311ha92fb03_0
    - openssl 3.1.3 h53f4e23_0
    - packaging 23.1 pyhd8ed1ab_0
    - pip 23.2.1 pyhd8ed1ab_0
    - pybind11 2.11.1 py311he4fd1f5_1
    - pybind11-global 2.11.1 py311he4fd1f5_1
    - python 3.11.5 h47c9636_0_cpython
    - python_abi 3.11 4_cp311
    - readline 8.2 h92ec313_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - setuptools-scm 7.1.0 pyhd8ed1ab_0
    - setuptools_scm 7.1.0 hd8ed1ab_0
    - setuptools_scm_git_archive 1.4.1 pyhd8ed1ab_0
    - tk 8.6.12 he1e0b03_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.8.0 hd8ed1ab_0
    - typing_extensions 4.8.0 pyha770c72_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.2 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
    - zlib 1.2.13 h53f4e23_5
  run:
    - certifi >=2020.06.20
    - contourpy >=1.0.1
    - cycler >=0.10
    - fonttools >=4.22.0
    - freetype >=2.12.1,<3.0a0
    - kiwisolver >=1.0.1
    - libcxx >=15.0.7
    - numpy >=1.21,<2
    - numpy >=1.23.5,<2.0a0
    - packaging >=20.0
    - pillow >=6.2.0
    - pyparsing >=2.3.1
    - python >=3.11,<3.12.0a0
    - python >=3.11,<3.12.0a0 *_cpython
    - python-dateutil >=2.7
    - python_abi 3.11.* *_cp311
test:
  imports:
    - matplotlib
    - matplotlib._image
    - matplotlib._path
    - matplotlib._qhull
    - matplotlib._tri
    - matplotlib._ttconv
    - matplotlib.backends._backend_agg
    - matplotlib.backends._tkagg
    - matplotlib.ft2font
    - matplotlib.pyplot
    - mpl_toolkits
    - pylab
about:
  description: 'matplotlib is a python 2D plotting library which produces publication

    quality figures in a variety of hardcopy formats and interactive

    environments across platforms. matplotlib can be used in Python scripts,

    the Python and IPython shell (ala MATLAB or Mathematica), web

    application servers, and six graphical user interface toolkits.

    '
  dev_url: https://github.com/matplotlib/matplotlib/
  doc_url: http://matplotlib.org/contents.html
  home: http://matplotlib.org/
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE/LICENSE
  license_url: http://matplotlib.sourceforge.net/users/license.html
  summary: Publication quality figures in Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - dopplershift
    - mdboom
    - ocefpaf
    - pelson
    - tacaswell
