# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Oct  9 09:05:55 2023
# ------------------------------------------------

package:
  name: c-ares
  version: 1.20.1
source:
  sha256: de24a314844cb157909730828560628704f4f896d167dd7da0fa2fb93ea18b10
  url: https://c-ares.haxx.se/download/c-ares-1.20.1.tar.gz
build:
  number: '0'
  run_exports:
    - c-ares >=1.20.1,<2.0a0
  string: h93a5062_0
requirements:
  build:
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 ha1c5b94_14
    - cctools_osx-arm64 973.0.1 h7bb7a8e_14
    - clang 16.0.6 hc177806_1
    - clang-16 16.0.6 default_h762fdd7_1
    - clang_osx-arm64 16.0.6 ha81d56d_1
    - clangxx 16.0.6 default_h762fdd7_1
    - cmake-no-system 3.27.7 h93d8f39_0
    - compiler-rt 16.0.6 he1888fc_0
    - compiler-rt_osx-64 16.0.6 he1888fc_0
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 609 ha20a434_14
    - ld64_osx-arm64 609 h6aa3cc8_14
    - libclang-cpp16 16.0.6 default_h762fdd7_1
    - libcxx 16.0.6 hd57cbcb_0
    - libiconv 1.17 hac89ed1_0
    - libllvm16 16.0.6 he4b1e75_2
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 16.0.6 he4b1e75_2
    - ninja 1.11.1 hb8565cd_0
    - openssl 3.1.3 h8a1eda9_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  run: []
  run_constraint:
    - c-ares-static <0a0
about:
  home: https://c-ares.haxx.se/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: This is c-ares, an asynchronous resolver library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
    - wesm
    - xhochy
