# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Tue Sep 19 18:12:18 2023
# ------------------------------------------------

package:
  name: python_abi
  version: '3.11'
build:
  number: '4'
  string: 4_cp311
requirements:
  build: []
  run: []
  run_constrained:
    - python 3.11.* *_cpython
test:
  commands:
    - echo "hello"
about:
  home: https://github.com/conda-forge/python_abi-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Metapackage to select python implementation
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - chrisburr
    - isuruf
