# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sun Oct  1 08:33:09 2023
# ------------------------------------------------

package:
  name: pillow
  version: 10.0.1
source:
  patches:
    - patches/0001-Build-without-USE_WIN32_FILEIO.patch
    - patches/0002-Added-patch-to-fix-failing-Windows-test.patch
    - patches/0003-add-WEBP_ROOT-XCB_ROOT.patch
  sha256: 5df55f87434f1b42d9ebe4247ed50a0f0742cd1ad5be2820e3d1b1f4b4bc696f
  url: https://github.com/python-pillow/Pillow/archive/refs/tags/10.0.1.tar.gz
build:
  number: '2'
  string: py311h8dc27b9_2
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 habff3f6_14
    - cctools_osx-arm64 973.0.1 h2f5fd4a_14
    - clang 15.0.7 h694c41f_3
    - clang-15 15.0.7 default_hdb78580_3
    - clang_osx-arm64 15.0.7 h1cd4f45_3
    - clangxx 15.0.7 default_hdb78580_3
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - cross-python_osx-arm64 3.11 41_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - gettext 0.21.1 h8a4c099_0
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 609 h0fd476b_14
    - ld64_osx-arm64 609 he51b688_14
    - libclang-cpp15 15.0.7 default_hdb78580_3
    - libcxx 16.0.6 hd57cbcb_0
    - libexpat 2.5.0 hf0c8a7f_1
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_3
    - libsqlite 3.43.0 h58db7d2_0
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 15.0.7 he4b1e75_3
    - lz4-c 1.9.4 hf0c8a7f_0
    - ncurses 6.4 hf0c8a7f_0
    - openssl 3.1.3 h8a1eda9_0
    - popt 1.16 h7b079dc_2002
    - python 3.11.5 h30d4d87_0_cpython
    - readline 8.2 h9e318b2_1
    - rsync 3.2.7 h30d983d_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.13 hef22860_0
    - tzdata 2023c h71feb2d_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2023.7.22 hf0a4a13_0
    - freetype 2.12.1 hadb7bae_2
    - giflib 5.2.1 h1a8c8d9_3
    - lcms2 2.15 hf2736f0_3
    - lerc 4.0.0 h9a09cb3_0
    - libcxx 16.0.6 h4653b0c_0
    - libdeflate 1.19 hb547adb_0
    - libexpat 2.5.0 hb7217d7_1
    - libffi 3.4.2 h3422bc3_5
    - libjpeg-turbo 3.0.0 hb547adb_1
    - libpng 1.6.39 h76d750c_0
    - libsqlite 3.43.0 hb31c410_0
    - libtiff 4.6.0 ha8a6c65_2
    - libwebp 1.3.2 hf30222e_1
    - libwebp-base 1.3.2 hb547adb_0
    - libxcb 1.15 hf346824_0
    - libzlib 1.2.13 h53f4e23_5
    - ncurses 6.4 h7ea286d_0
    - openjpeg 2.5.0 h4c1507b_3
    - openssl 3.1.3 h53f4e23_0
    - pip 23.2.1 pyhd8ed1ab_0
    - pthread-stubs 0.4 h27ca646_1001
    - python 3.11.5 h47c9636_0_cpython
    - readline 8.2 h92ec313_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - tk 8.6.13 hb31c410_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.2 pyhd8ed1ab_0
    - xorg-libxau 1.0.11 hb547adb_0
    - xorg-libxdmcp 1.1.3 h27ca646_0
    - xz 5.2.6 h57fd34a_0
    - zlib 1.2.13 h53f4e23_5
    - zstd 1.5.5 h4f39d0f_0
  run:
    - freetype >=2.12.1,<3.0a0
    - lcms2 >=2.15,<3.0a0
    - libjpeg-turbo >=3.0.0,<4.0a0
    - libtiff >=4.6.0,<4.7.0a0
    - libwebp-base >=1.3.2,<2.0a0
    - libxcb >=1.15,<1.16.0a0
    - libzlib >=1.2.13,<1.3.0a0
    - openjpeg >=2.5.0,<3.0a0
    - python >=3.11,<3.12.0a0
    - python >=3.11,<3.12.0a0 *_cpython
    - python_abi 3.11.* *_cp311
    - tk >=8.6.13,<8.7.0a0
test:
  commands:
    - pytest -v -k "not (_not_a_real_test or test_tiff_crashes[Tests/images/crash-81154a65438ba5aaeca73fd502fa4850fbde60f8.tif])"
  files:
    - Tests/images
  imports:
    - PIL
    - PIL.Image
    - PIL.ImageCms
  requires:
    - aiohttp
    - clang_osx-arm64 15.*
    - fsspec
    - pytest
    - pytest-timeout
    - requests
    - setuptools
  source_files:
    - Tests/
about:
  dev_url: https://github.com/python-pillow/Pillow/
  home: https://pillow.readthedocs.io
  license: HPND
  license_file: LICENSE
  summary: Pillow is the friendly PIL fork by Alex Clark and Contributors
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - h-vetinari
    - jakirkham
    - ocefpaf
    - patricksnape
    - pelson
