# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Tue Jun  6 18:33:15 2023
# ------------------------------------------------

package:
  name: ncurses
  version: '6.4'
source:
  fn: ncurses-6.4.tar.gz
  sha256: 6931283d9ac87c5073f30b6290c4c75f21632bb4fc3603ac8100812bed248159
  url: http://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.4.tar.gz
build:
  ignore_run_exports:
    - libcxx
    - libstdcxx-ng
  number: '0'
  run_exports:
    - ncurses >=6.4,<7.0a0
  string: h7ea286d_0
requirements:
  build:
    - ca-certificates 2023.5.7 h8857fd0_0
    - cctools_osx-64 973.0.1 hcc6d90d_13
    - cctools_osx-arm64 973.0.1 hfd1dfa6_13
    - clang 14.0.6 h694c41f_1
    - clang-14 14.0.6 default_hdb78580_1
    - clang_osx-arm64 14.0.6 he41d1a2_6
    - clangxx 14.0.6 default_hdb78580_1
    - clangxx_osx-arm64 14.0.6 h748fd88_6
    - compiler-rt 14.0.6 h613da45_0
    - compiler-rt_osx-64 14.0.6 hab78ec2_0
    - coreutils 9.3 hb7f2c08_0
    - ld64_osx-64 609 hfd63004_13
    - ld64_osx-arm64 609 h566df06_13
    - libclang-cpp14 14.0.6 default_hdb78580_1
    - libcxx 16.0.5 hd57cbcb_0
    - libiconv 1.17 hac89ed1_0
    - libllvm14 14.0.6 hc8e404f_3
    - libtool 2.4.7 hf0c8a7f_0
    - libzlib 1.2.13 hfd90126_4
    - llvm-tools 14.0.6 hc8e404f_3
    - make 4.3 h22f3db7_1
    - ncurses
    - openssl 3.1.1 h8a1eda9_1
    - pkg-config 0.29.2 ha3d46e9_1008
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
  host:
    - libcxx 16.0.5 h4653b0c_0
  run: []
test:
  commands:
    - test ! -f ${PREFIX}/lib/libncurses.a
    - test ! -f ${PREFIX}/lib/libncursesw.a
    - test -f ${PREFIX}/lib/libncurses.dylib
    - test -f ${PREFIX}/lib/libncursesw.dylib
    - test ! -f ${PREFIX}/lib/libtinfo.a
    - test ! -f ${PREFIX}/lib/libtinfow.a
    - test -f ${PREFIX}/lib/libtinfo.dylib
    - test -f ${PREFIX}/lib/libtinfow.dylib
    - test ! -f ${PREFIX}/lib/libform.a
    - test ! -f ${PREFIX}/lib/libformw.a
    - test -f ${PREFIX}/lib/libform.dylib
    - test -f ${PREFIX}/lib/libformw.dylib
    - test ! -f ${PREFIX}/lib/libmenu.a
    - test ! -f ${PREFIX}/lib/libmenuw.a
    - test -f ${PREFIX}/lib/libmenu.dylib
    - test -f ${PREFIX}/lib/libmenuw.dylib
    - test ! -f ${PREFIX}/lib/libpanel.a
    - test ! -f ${PREFIX}/lib/libpanelw.a
    - test -f ${PREFIX}/lib/libpanel.dylib
    - test -f ${PREFIX}/lib/libpanelw.dylib
    - test -d ${PREFIX}/include/ncurses
    - test -d ${PREFIX}/include/ncursesw
    - test -L ${PREFIX}/include/ncurses/curses.h
    - test -L ${PREFIX}/include/ncursesw/curses.h
    - test -f ${PREFIX}/include/curses.h
    - test -L ${PREFIX}/include/ncurses/cursesapp.h
    - test -L ${PREFIX}/include/ncursesw/cursesapp.h
    - test -f ${PREFIX}/include/cursesapp.h
    - test -L ${PREFIX}/include/ncurses/cursesf.h
    - test -L ${PREFIX}/include/ncursesw/cursesf.h
    - test -f ${PREFIX}/include/cursesf.h
    - test -L ${PREFIX}/include/ncurses/cursesm.h
    - test -L ${PREFIX}/include/ncursesw/cursesm.h
    - test -f ${PREFIX}/include/cursesm.h
    - test -L ${PREFIX}/include/ncurses/cursesp.h
    - test -L ${PREFIX}/include/ncursesw/cursesp.h
    - test -f ${PREFIX}/include/cursesp.h
    - test -L ${PREFIX}/include/ncurses/cursesw.h
    - test -L ${PREFIX}/include/ncursesw/cursesw.h
    - test -f ${PREFIX}/include/cursesw.h
    - test -L ${PREFIX}/include/ncurses/cursslk.h
    - test -L ${PREFIX}/include/ncursesw/cursslk.h
    - test -f ${PREFIX}/include/cursslk.h
    - test -L ${PREFIX}/include/ncurses/eti.h
    - test -L ${PREFIX}/include/ncursesw/eti.h
    - test -f ${PREFIX}/include/eti.h
    - test -L ${PREFIX}/include/ncurses/etip.h
    - test -L ${PREFIX}/include/ncursesw/etip.h
    - test -f ${PREFIX}/include/etip.h
    - test -L ${PREFIX}/include/ncurses/form.h
    - test -L ${PREFIX}/include/ncursesw/form.h
    - test -f ${PREFIX}/include/form.h
    - test -L ${PREFIX}/include/ncurses/menu.h
    - test -L ${PREFIX}/include/ncursesw/menu.h
    - test -f ${PREFIX}/include/menu.h
    - test -L ${PREFIX}/include/ncurses/nc_tparm.h
    - test -L ${PREFIX}/include/ncursesw/nc_tparm.h
    - test -f ${PREFIX}/include/nc_tparm.h
    - test -L ${PREFIX}/include/ncurses/ncurses.h
    - test -L ${PREFIX}/include/ncursesw/ncurses.h
    - test -f ${PREFIX}/include/ncurses.h
    - test -L ${PREFIX}/include/ncurses/ncurses_dll.h
    - test -L ${PREFIX}/include/ncursesw/ncurses_dll.h
    - test -f ${PREFIX}/include/ncurses_dll.h
    - test -L ${PREFIX}/include/ncurses/panel.h
    - test -L ${PREFIX}/include/ncursesw/panel.h
    - test -f ${PREFIX}/include/panel.h
    - test -L ${PREFIX}/include/ncurses/term.h
    - test -L ${PREFIX}/include/ncursesw/term.h
    - test -f ${PREFIX}/include/term.h
    - test -L ${PREFIX}/include/ncurses/term_entry.h
    - test -L ${PREFIX}/include/ncursesw/term_entry.h
    - test -f ${PREFIX}/include/term_entry.h
    - test -L ${PREFIX}/include/ncurses/termcap.h
    - test -L ${PREFIX}/include/ncursesw/termcap.h
    - test -f ${PREFIX}/include/termcap.h
    - test -L ${PREFIX}/include/ncurses/tic.h
    - test -L ${PREFIX}/include/ncursesw/tic.h
    - test -f ${PREFIX}/include/tic.h
    - test -L ${PREFIX}/include/ncurses/unctrl.h
    - test -L ${PREFIX}/include/ncursesw/unctrl.h
    - test -f ${PREFIX}/include/unctrl.h
    - test -f ${PREFIX}/lib/pkgconfig/form.pc
    - cat ${PREFIX}/lib/pkgconfig/form.pc
    - test -f ${PREFIX}/lib/pkgconfig/formw.pc
    - cat ${PREFIX}/lib/pkgconfig/formw.pc
    - test -f ${PREFIX}/lib/pkgconfig/menu.pc
    - cat ${PREFIX}/lib/pkgconfig/menu.pc
    - test -f ${PREFIX}/lib/pkgconfig/menuw.pc
    - cat ${PREFIX}/lib/pkgconfig/menuw.pc
    - test -f ${PREFIX}/lib/pkgconfig/ncurses++.pc
    - cat ${PREFIX}/lib/pkgconfig/ncurses++.pc
    - test -f ${PREFIX}/lib/pkgconfig/ncurses++w.pc
    - cat ${PREFIX}/lib/pkgconfig/ncurses++w.pc
    - test -f ${PREFIX}/lib/pkgconfig/ncurses.pc
    - cat ${PREFIX}/lib/pkgconfig/ncurses.pc
    - test -f ${PREFIX}/lib/pkgconfig/ncursesw.pc
    - cat ${PREFIX}/lib/pkgconfig/ncursesw.pc
    - test -f ${PREFIX}/lib/pkgconfig/panel.pc
    - cat ${PREFIX}/lib/pkgconfig/panel.pc
    - test -f ${PREFIX}/lib/pkgconfig/panelw.pc
    - cat ${PREFIX}/lib/pkgconfig/panelw.pc
    - test -f ${PREFIX}/lib/pkgconfig/tinfo.pc
    - cat ${PREFIX}/lib/pkgconfig/tinfo.pc
    - test -f ${PREFIX}/lib/pkgconfig/tinfow.pc
    - cat ${PREFIX}/lib/pkgconfig/tinfow.pc
    - pkg-config ncurses --libs
    - pkg-config ncurses --libs | grep "^-L${PREFIX}/lib .*-lncurses -ltinfo$"
    - pkg-config tinfo --libs | grep "^-L${PREFIX}/lib .*-ltinfo$"
    - pkg-config ncursesw --libs | grep "^-L${PREFIX}/lib .*-lncursesw -ltinfow$"
    - pkg-config tinfow --libs | grep "^-L${PREFIX}/lib .*-ltinfow$"
  requires:
    - pkg-config
about:
  description: 'The ncurses (new curses) library is a free software

    emulation of curses in System V Release 4.0 (SVr4),

    and more. It uses terminfo format, supports pads and

    color and multiple highlights and forms characters and

    function-key mapping, and has all the other SVr4-curses

    enhancements over BSD curses. SVr4 curses is better

    known today as X/Open Curses

    '
  dev_url: http://invisible-island.net/ncurses/
  doc_url: http://invisible-island.net/ncurses/NCURSES-Programming-HOWTO.html
  home: http://www.gnu.org/software/ncurses/
  license: X11 AND BSD-3-Clause
  license_file: COPYING
  summary: Library for text-based user interfaces
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - fhoehle
    - jakirkham
    - mingwandroid
