# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sun Sep 24 11:14:13 2023
# ------------------------------------------------

package:
  name: contourpy
  version: 1.1.1
source:
  sha256: 96ba37c2e24b7212a77da85004c38e7c4d155d3e72a45eeaf22c1f03f607e8ab
  url: https://pypi.io/packages/source/c/contourpy/contourpy-1.1.1.tar.gz
build:
  number: '1'
  string: py311he4fd1f5_1
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 habff3f6_14
    - cctools_osx-arm64 973.0.1 h2f5fd4a_14
    - clang 15.0.7 h694c41f_3
    - clang-15 15.0.7 default_hdb78580_3
    - clang_osx-arm64 15.0.7 h1cd4f45_3
    - clangxx 15.0.7 default_hdb78580_3
    - clangxx_osx-arm64 15.0.7 hc662a55_3
    - colorama 0.4.6 pyhd8ed1ab_0
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - cross-python_osx-arm64 3.11 41_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - gettext 0.21.1 h8a4c099_0
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 609 h0fd476b_14
    - ld64_osx-arm64 609 he51b688_14
    - libclang-cpp15 15.0.7 default_hdb78580_3
    - libcxx 16.0.6 hd57cbcb_0
    - libexpat 2.5.0 hf0c8a7f_1
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_3
    - libsqlite 3.43.0 h58db7d2_0
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 15.0.7 he4b1e75_3
    - lz4-c 1.9.4 hf0c8a7f_0
    - meson 1.2.1 pyhd8ed1ab_0
    - meson-python 0.14.0 pyh0c530f3_0
    - ncurses 6.4 hf0c8a7f_0
    - ninja 1.11.1 hb8565cd_0
    - openssl 3.1.3 h8a1eda9_0
    - packaging 23.1 pyhd8ed1ab_0
    - popt 1.16 h7b079dc_2002
    - pybind11 2.11.1 py311h5fe6e05_2
    - pybind11-global 2.11.1 py311h5fe6e05_2
    - pyproject-metadata 0.7.1 pyhd8ed1ab_0
    - python 3.11.5 h30d4d87_0_cpython
    - python_abi 3.11 4_cp311
    - readline 8.2 h9e318b2_1
    - rsync 3.2.7 h30d983d_0
    - sed 4.7 h3efe00b_1000
    - setuptools 68.2.2 pyhd8ed1ab_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.13 hef22860_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - tzdata 2023c h71feb2d_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2023.7.22 hf0a4a13_0
    - colorama 0.4.6 pyhd8ed1ab_0
    - libcxx 16.0.6 h4653b0c_0
    - libexpat 2.5.0 hb7217d7_1
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.43.0 hb31c410_0
    - libzlib 1.2.13 h53f4e23_5
    - meson 1.2.1 pyhd8ed1ab_0
    - meson-python 0.14.0 pyh0c530f3_0
    - ncurses 6.4 h7ea286d_0
    - ninja 1.11.1 hffc8910_0
    - openssl 3.1.3 h53f4e23_0
    - packaging 23.1 pyhd8ed1ab_0
    - pip 23.2.1 pyhd8ed1ab_0
    - pybind11 2.11.1 py311he4fd1f5_2
    - pybind11-global 2.11.1 py311he4fd1f5_2
    - pyproject-metadata 0.7.1 pyhd8ed1ab_0
    - python 3.11.5 h47c9636_0_cpython
    - python_abi 3.11 4_cp311
    - readline 8.2 h92ec313_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - tk 8.6.13 hb31c410_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.2 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
  run:
    - libcxx >=15.0.7
    - numpy >=1.16
    - python >=3.11,<3.12.0a0
    - python >=3.11,<3.12.0a0 *_cpython
    - python_abi 3.11.* *_cp311
test:
  commands:
    - pip check
    - python -c "import contourpy as c; print(c.contour_generator(z=[[0, 1], [2, 3]]).lines(0.9))"
    - python -c "from contourpy.util import build_config; from pprint import pprint;
      pprint(build_config())"
    - python -c "import platform, sys; print(sys.version, platform.uname())"
  imports:
    - contourpy
    - contourpy.util
  requires:
    - pip
about:
  description: 'ContourPy is a Python library for calculating contours of 2D quadrilateral

    grids.  It is written in C++11 and wrapped using pybind11.

    '
  doc_url: https://contourpy.readthedocs.io
  home: https://github.com/contourpy/contourpy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python library for calculating contours of 2D quadrilateral grids.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ianthomas23
