# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Thu Oct  5 02:42:45 2023
# ------------------------------------------------

package:
  name: libaec
  version: 1.1.2
source:
  patches:
    - 0001-Disable-building-the-static-library.patch
  sha256: cde2097c6e0f18dbc4771930cebe907dfbdfcb7921f74d2594d46221581b6ef1
  url: https://gitlab.dkrz.de/k202009/libaec/-/archive/v1.1.2/libaec-v1.1.2.tar.gz
build:
  number: '1'
  run_exports:
    - libaec >=1.1.2,<2.0a0
  string: h13dd4ca_1
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - c-ares 1.19.1 h0dc2134_0
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 habff3f6_14
    - cctools_osx-arm64 973.0.1 h2f5fd4a_14
    - clang 15.0.7 h694c41f_3
    - clang-15 15.0.7 default_hdb78580_3
    - clang_osx-arm64 15.0.7 h1cd4f45_3
    - clangxx 15.0.7 default_hdb78580_3
    - clangxx_osx-arm64 15.0.7 hc662a55_3
    - cmake 3.27.6 hf40c264_0
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - icu 73.2 hf5e326d_0
    - krb5 1.21.2 hb884880_0
    - ld64_osx-64 609 h0fd476b_14
    - ld64_osx-arm64 609 he51b688_14
    - libclang-cpp15 15.0.7 default_hdb78580_3
    - libcurl 8.3.0 h5f667d7_0
    - libcxx 16.0.6 hd57cbcb_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 haf1e3a3_1
    - libexpat 2.5.0 hf0c8a7f_1
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_3
    - libnghttp2 1.52.0 he2ab024_0
    - libssh2 1.11.0 hd019ec5_0
    - libuv 1.46.0 h0c2f820_0
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 15.0.7 he4b1e75_3
    - make 4.3 h22f3db7_1
    - ncurses 6.4 hf0c8a7f_0
    - openssl 3.1.3 h8a1eda9_0
    - rhash 1.4.4 h0dc2134_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - libcxx 16.0.6 h4653b0c_0
  run:
    - libcxx >=15.0.7
test:
  commands:
    - test -f ${PREFIX}/lib/libaec${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libsz${SHLIB_EXT}
about:
  description: 'Libaec provides fast lossless compression of 1 up to 32 bit wide signed
    or unsigned integers (samples).

    The library achieves best results for low entropy data as often encountered in
    space imaging instrument

    data or numerical model output from weather or climate simulations. While floating
    point representations

    are not directly supported, they can also be efficiently coded by grouping exponents
    and mantissa.

    Libaec implements Golomb-Rice coding as defined in the Space Data System Standard
    documents 121.0-B-2

    and 120.0-G-2.

    '
  dev_url: https://gitlab.dkrz.de/k202009/libaec
  home: https://gitlab.dkrz.de/k202009/libaec
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Adaptive Entropy Coding library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - hmaarrfk
    - kmuehlbauer
