# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Oct  1 23:18:33 2023
# ------------------------------------------------

package:
  name: packaging
  version: '23.2'
source:
  sha256: 048fb0e9405036518eaaf48a55953c750c11e1a1b68e0dd1a9d62ed0c092cfc5
  url: https://pypi.io/packages/source/p/packaging/packaging-23.2.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/packaging_1696202382185/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - brotli-python 1.1.0 py311hb755f60_1
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2023.7.22 hbcca054_0
    - certifi 2023.7.22 pyhd8ed1ab_0
    - charset-normalizer 3.2.0 pyhd8ed1ab_0
    - docutils 0.20.1 py311h38be061_2
    - flit 3.9.0 pyhd8ed1ab_0
    - flit-core 3.9.0 pyhd8ed1ab_0
    - idna 3.4 pyhd8ed1ab_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_2
    - libgomp 13.2.0 h807b86a_2
    - libnsl 2.0.0 hd590300_1
    - libsqlite 3.43.0 h2797004_0
    - libstdcxx-ng 13.2.0 h7e041cc_2
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.3 hd590300_0
    - pip 23.2.1 pyhd8ed1ab_0
    - pysocks 1.7.1 pyha2e5f31_6
    - python 3.11.5 hab00c5b_0_cpython
    - python_abi 3.11 4_cp311
    - readline 8.2 h8228510_1
    - requests 2.31.0 pyhd8ed1ab_0
    - setuptools 68.2.2 pyhd8ed1ab_0
    - tk 8.6.13 h2797004_0
    - tomli-w 1.0.0 pyhd8ed1ab_0
    - tzdata 2023c h71feb2d_0
    - urllib3 2.0.5 pyhd8ed1ab_0
    - wheel 0.41.2 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.7
test:
  commands:
    - pip check
  imports:
    - packaging
  requires:
    - pip
about:
  home: https://github.com/pypa/packaging
  license: Apache-2.0
  license_file: LICENSE
  summary: Core utilities for Python packages
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - nicoddemus
