# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sun Sep 17 03:05:42 2023
# ------------------------------------------------

package:
  name: numpy
  version: 1.26.0
source:
  - sha256: f93fc78fe8bf15afe2b8d6b6499f1c73953169fad1e9a8dd086cdff3190e7fdf
    url: https://github.com/numpy/numpy/releases/download/v1.26.0/numpy-1.26.0.tar.gz
build:
  entry_points: null
  number: '0'
  run_exports:
    - numpy >=1.26.0,<2.0a0
  string: py311hb8f3215_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 habff3f6_14
    - cctools_osx-arm64 973.0.1 h2f5fd4a_14
    - clang 15.0.7 h694c41f_3
    - clang-15 15.0.7 default_hdb78580_3
    - clang_osx-arm64 15.0.7 h1cd4f45_3
    - clangxx 15.0.7 default_hdb78580_3
    - clangxx_osx-arm64 15.0.7 hc662a55_3
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - cross-python_osx-arm64 3.11 40_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - cython 3.0.2 py311hdf8f085_0
    - gettext 0.21.1 h8a4c099_0
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 609 h0fd476b_14
    - ld64_osx-arm64 609 he51b688_14
    - libclang-cpp15 15.0.7 default_hdb78580_3
    - libcxx 16.0.6 hd57cbcb_0
    - libexpat 2.5.0 hf0c8a7f_1
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_3
    - libsqlite 3.43.0 h58db7d2_0
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 15.0.7 he4b1e75_3
    - lz4-c 1.9.4 hf0c8a7f_0
    - ncurses 6.4 hf0c8a7f_0
    - ninja 1.11.1 hb8565cd_0
    - openssl 3.1.2 h8a1eda9_0
    - pkg-config 0.29.2 ha3d46e9_1008
    - popt 1.16 h7b079dc_2002
    - python 3.11.5 h30d4d87_0_cpython
    - python_abi 3.11 3_cp311
    - readline 8.2 h9e318b2_1
    - rsync 3.2.7 h30d983d_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2023c h71feb2d_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2023.7.22 hf0a4a13_0
    - colorama 0.4.6 pyhd8ed1ab_0
    - cython 3.0.2 py311ha891d26_0
    - gettext 0.21.1 h0186832_0
    - importlib-metadata 6.8.0 pyha770c72_0
    - libblas 3.9.0 5_h880f123_netlib
    - libcblas 3.9.0 5_h880f123_netlib
    - libcxx 16.0.6 h4653b0c_0
    - libexpat 2.5.0 hb7217d7_1
    - libffi 3.4.2 h3422bc3_5
    - libgfortran 5.0.0 13_2_0_hd922786_1
    - libgfortran5 13.2.0 hf226fd6_1
    - libglib 2.78.0 h24e9cb9_0
    - libiconv 1.17 he4db4b2_0
    - liblapack 3.9.0 5_h880f123_netlib
    - libsqlite 3.43.0 hb31c410_0
    - libzlib 1.2.13 h53f4e23_5
    - llvm-openmp 16.0.6 h1c12783_0
    - ncurses 6.4 h7ea286d_0
    - ninja 1.11.1 hffc8910_0
    - openssl 3.1.2 h53f4e23_0
    - packaging 23.1 pyhd8ed1ab_0
    - pcre2 10.40 hb34f9b4_0
    - pip 23.2.1 pyhd8ed1ab_0
    - pkg-config 0.29.2 hab62308_1008
    - pyproject-metadata 0.7.1 pyhd8ed1ab_0
    - pyproject_hooks 1.0.0 pyhd8ed1ab_0
    - python 3.11.5 h47c9636_0_cpython
    - python-build 1.0.3 pyhd8ed1ab_0
    - python_abi 3.11 3_cp311
    - readline 8.2 h92ec313_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - tk 8.6.12 he1e0b03_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.2 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
    - zipp 3.16.2 pyhd8ed1ab_0
  run:
    - libblas >=3.9.0,<4.0a0
    - libcblas >=3.9.0,<4.0a0
    - libcxx >=15.0.7
    - liblapack >=3.9.0,<4.0a0
    - python >=3.11,<3.12.0a0
    - python >=3.11,<3.12.0a0 *_cpython
    - python_abi 3.11.* *_cp311
  run_constrained:
    - numpy-base <0a0
test:
  commands:
    - f2py -h
    - python -c "import numpy, sys; sys.exit(not numpy.test(verbose=1, label='full',
      tests=None, extra_argv=['-k', 'not (_not_a_real_test or Test_ARM_Features or
      Test_POWER_Features or test_new_policy)', '-nauto', '--timeout=3000', '--durations=50']))"
  imports:
    - numpy
    - numpy.array_api
    - numpy.array_api.linalg
    - numpy.core.multiarray
    - numpy.core.numeric
    - numpy.core.umath
    - numpy.ctypeslib
    - numpy.distutils
    - numpy.dtypes
    - numpy.exceptions
    - numpy.f2py
    - numpy.fft
    - numpy.lib
    - numpy.lib.mixins
    - numpy.lib.recfunctions
    - numpy.lib.scimath
    - numpy.linalg
    - numpy.linalg.lapack_lite
    - numpy.ma
    - numpy.ma.extras
    - numpy.ma.mrecords
    - numpy.matlib
    - numpy.polynomial
    - numpy.random
    - numpy.random.mtrand
    - numpy.testing
    - numpy.typing
    - numpy.version
  requires:
    - cython
    - hypothesis
    - meson
    - pytest
    - pytest-timeout
    - pytest-xdist
    - pytz
    - setuptools <60.0.0
    - typing_extensions
about:
  dev_url: https://github.com/numpy/numpy
  doc_url: https://numpy.org/doc/stable/
  home: http://numpy.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: The fundamental package for scientific computing with Python.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - h-vetinari
    - isuruf
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
    - rgommers
    - xhochy
