# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Oct  9 21:20:58 2023
# ------------------------------------------------

package:
  name: h5py
  version: 3.10.0
source:
  sha256: 9cac7838ab139ec71adf721a1305b954e18efa4f80c82fcfe34e1eb9639ded29
  url: https://github.com/h5py/h5py/archive/3.10.0.tar.gz
build:
  number: '100'
  script_env:
    - HDF5_HAS_ROS3=1
  string: nompi_py311h393cb7e_100
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - c-ares 1.20.1 h10d778d_0
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 ha1c5b94_14
    - cctools_osx-arm64 973.0.1 h7bb7a8e_14
    - clang 16.0.6 hc177806_1
    - clang-16 16.0.6 default_h762fdd7_1
    - clang_osx-arm64 16.0.6 ha81d56d_1
    - clangxx 16.0.6 default_h762fdd7_1
    - compiler-rt 16.0.6 he1888fc_0
    - compiler-rt_osx-64 16.0.6 he1888fc_0
    - cross-python_osx-arm64 3.11 41_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - cython 0.29.36 py311hdf8f085_1
    - gettext 0.21.1 h8a4c099_0
    - hdf5 1.14.2 nompi_hedada53_100
    - icu 73.2 hf5e326d_0
    - krb5 1.21.2 hb884880_0
    - ld64_osx-64 609 ha20a434_14
    - ld64_osx-arm64 609 h6aa3cc8_14
    - libaec 1.1.2 he965462_1
    - libblas 3.9.0 18_osx64_openblas
    - libcblas 3.9.0 18_osx64_openblas
    - libclang-cpp16 16.0.6 default_h762fdd7_1
    - libcurl 8.3.0 h5f667d7_0
    - libcxx 16.0.6 hd57cbcb_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 haf1e3a3_1
    - libexpat 2.5.0 hf0c8a7f_1
    - libffi 3.4.2 h0d85af4_5
    - libgfortran 5.0.0 13_2_0_h97931a8_1
    - libgfortran5 13.2.0 h2873a65_1
    - libiconv 1.17 hac89ed1_0
    - liblapack 3.9.0 18_osx64_openblas
    - libllvm16 16.0.6 he4b1e75_2
    - libnghttp2 1.52.0 he2ab024_0
    - libopenblas 0.3.24 openmp_h48a4ad5_0
    - libsqlite 3.43.0 h58db7d2_0
    - libssh2 1.11.0 hd019ec5_0
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-openmp 17.0.2 hff08bdf_0
    - llvm-tools 16.0.6 he4b1e75_2
    - lz4-c 1.9.4 hf0c8a7f_0
    - ncurses 6.4 hf0c8a7f_0
    - numpy 1.23.5 py311h62c7003_0
    - openssl 3.1.3 h8a1eda9_0
    - popt 1.16 h7b079dc_2002
    - python 3.11.6 h30d4d87_0_cpython
    - python_abi 3.11 4_cp311
    - readline 8.2 h9e318b2_1
    - rsync 3.2.7 h30d983d_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.13 hef22860_0
    - tzdata 2023c h71feb2d_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - bzip2 1.0.8 h3422bc3_4
    - c-ares 1.20.1 h93a5062_0
    - ca-certificates 2023.7.22 hf0a4a13_0
    - cython 0.29.36 py311ha891d26_1
    - gettext 0.21.1 h0186832_0
    - hdf5 1.14.2 nompi_h3aba7b3_100
    - krb5 1.21.2 h92f50d5_0
    - libaec 1.1.2 h13dd4ca_1
    - libblas 3.9.0 18_osxarm64_openblas
    - libcblas 3.9.0 18_osxarm64_openblas
    - libcurl 8.3.0 hc52a3a8_0
    - libcxx 16.0.6 h4653b0c_0
    - libedit 3.1.20191231 hc8eb9b7_2
    - libev 4.33 h642e427_1
    - libexpat 2.5.0 hb7217d7_1
    - libffi 3.4.2 h3422bc3_5
    - libgfortran 5.0.0 13_2_0_hd922786_1
    - libgfortran5 13.2.0 hf226fd6_1
    - libglib 2.78.0 h24e9cb9_0
    - libiconv 1.17 he4db4b2_0
    - liblapack 3.9.0 18_osxarm64_openblas
    - libnghttp2 1.52.0 hae82a92_0
    - libopenblas 0.3.24 openmp_hd76b1f2_0
    - libsqlite 3.43.0 hb31c410_0
    - libssh2 1.11.0 h7a5bd25_0
    - libzlib 1.2.13 h53f4e23_5
    - llvm-openmp 17.0.2 h1c12783_0
    - ncurses 6.4 h7ea286d_0
    - numpy 1.23.5 py311ha92fb03_0
    - openssl 3.1.3 h53f4e23_0
    - pcre2 10.40 hb34f9b4_0
    - pip 23.2.1 pyhd8ed1ab_0
    - pkg-config 0.29.2 hab62308_1008
    - pkgconfig 1.5.5 pyhd8ed1ab_4
    - python 3.11.6 h47c9636_0_cpython
    - python_abi 3.11 4_cp311
    - readline 8.2 h92ec313_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - tk 8.6.13 hb31c410_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.2 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
    - zstd 1.5.5 h4f39d0f_0
  run:
    - cached-property
    - hdf5 >=1.14.2,<1.14.3.0a0
    - numpy >=1.23.5,<2.0a0
    - python >=3.11,<3.12.0a0
    - python >=3.11,<3.12.0a0 *_cpython
    - python_abi 3.11.* *_cp311
test:
  commands:
    - pip check
  imports:
    - h5py
  requires:
    - pip
    - pytest
    - pytest-mpi
about:
  dev_url: https://github.com/h5py/h5py
  home: http://www.h5py.org/
  license: BSD-3-Clause
  license_file: licenses/license.txt
  summary: Read and write HDF5 files from Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jan-janssen
    - minrk
    - ocefpaf
    - scopatz
    - tacaswell
