# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: libsqlite
  version: 3.43.2
source:
  patches: null
  sha256: 6d422b6f62c4de2ca80d61860e3a3fb693554d2f75bb1aaca743ccc4d6f609f0
  url: https://www.sqlite.org/2023/sqlite-autoconf-3430200.tar.gz
build:
  number: 0
  run_exports:
    - libsqlite >=3.43.2,<4.0a0
  string: h091b4b1_0
requirements:
  build:
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 ha1c5b94_14
    - cctools_osx-arm64 973.0.1 h7bb7a8e_14
    - clang 16.0.6 hc177806_1
    - clang-16 16.0.6 default_h762fdd7_1
    - clang_osx-arm64 16.0.6 ha81d56d_1
    - clangxx 16.0.6 default_h762fdd7_1
    - compiler-rt 16.0.6 he1888fc_0
    - compiler-rt_osx-64 16.0.6 he1888fc_0
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 609 ha20a434_14
    - ld64_osx-arm64 609 h6aa3cc8_14
    - libclang-cpp16 16.0.6 default_h762fdd7_1
    - libcxx 16.0.6 hd57cbcb_0
    - libiconv 1.17 hac89ed1_0
    - libllvm16 16.0.6 he4b1e75_2
    - libtool 2.4.7 hf0c8a7f_0
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 16.0.6 he4b1e75_2
    - make 4.3 h22f3db7_1
    - openssl 3.1.3 h8a1eda9_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - libzlib 1.2.13 h53f4e23_5
    - zlib 1.2.13 h53f4e23_5
  run:
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libsqlite3.a
    - test -f $PREFIX/include/sqlite3.h
    - test -f $PREFIX/include/sqlite3ext.h
about:
  description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

    public-domain, SQL database engine.It is the most used database engine

    in the world.

    '
  dev_url: https://github.com/mackyle/sqlite
  doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
  doc_url: http://www.sqlite.org/docs.html
  home: http://www.sqlite.org/
  license: Unlicense
  license_url: http://www.sqlite.org/copyright.html
  summary: Implements a self-contained, zero-configuration, SQL database engine
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - snorfalorpagus
