# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Mar 28 22:03:42 2023
# ------------------------------------------------

package:
  name: tzdata
  version: 2023c
source:
  - sha256: 3f510b5d1b4ae9bb38e485aa302a776b317fb3637bdb6404c4adf7b6cadd965c
    url: https://data.iana.org/time-zones/releases/tzdata2023c.tar.gz
  - sha256: 46d17f2bb19ad73290f03a203006152e0fa0d7b11e5b71467c4a823811b214e7
    url: https://data.iana.org/time-zones/releases/tzcode2023c.tar.gz
build:
  ignore_run_exports:
    - libgcc-ng
  noarch: generic
  number: '0'
  string: h71feb2d_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 h5bd9786_13
    - binutils_impl_linux-64 2.39 he00db2b_1
    - binutils_linux-64 2.39 h5fc0e48_12
    - gcc_impl_linux-64 11.3.0 hab1b70f_19
    - gcc_linux-64 11.3.0 he6f903b_12
    - kernel-headers_linux-64 3.10.0 h4a8ded7_13
    - ld_impl_linux-64 2.39 hcc3a1bd_1
    - libgcc-devel_linux-64 11.3.0 h210ce93_19
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libsanitizer 11.3.0 h239ccf8_19
    - libstdcxx-ng 12.2.0 h46fd767_19
    - make 4.3 hd18ef5c_1
    - sysroot_linux-64 2.17 h4a8ded7_13
  host:
    - __glibc >=2.17,<3.0.a0
  run: []
test:
  commands:
    - test -f "${PREFIX}/share/zoneinfo/leapseconds"
    - test -f "${PREFIX}/share/zoneinfo/iso3166.tab"
    - test -f "${PREFIX}/share/zoneinfo/zone1970.tab"
    - test -f "${PREFIX}/share/zoneinfo/zone.tab"
    - test -f "${PREFIX}/share/zoneinfo/tzdata.zi"
    - "dirs=\"$(\n  find \"${PREFIX}\" -mindepth 1 -maxdepth 2 \\\n  \\! -path \"\
      ${PREFIX}/share\" \\! -path \"${PREFIX}/conda-meta*\"\n)\"\ntest \"${dirs}\"\
      \ = \"${PREFIX}/share/zoneinfo\"\n"
    - "heads=\"$(\n  find \"${PREFIX}/share/zoneinfo\" -type f \\\n    \\! -name \\\
      *.zi \\! -name \\*.tab \\! -name leapseconds \\\n    -exec head -c4 {} \\; -printf\
      \ \\\\n \\\n    | uniq\n)\"\ntest \"${heads}\" = TZif\n"
about:
  description: 'The Time Zone Database (called tz, tzdb or zoneinfo) contains code

    (the tzcode package) and data (this package) that represent the

    history of local time for many representative

    locations around the globe.  It is updated periodically to reflect

    changes made by political bodies to time zone boundaries, UTC offsets,

    and daylight-saving rules.

    '
  dev_url: https://github.com/eggert/tz
  doc_url: https://data.iana.org/time-zones/tz-link.html
  home: https://www.iana.org/time-zones
  license: LicenseRef-Public-Domain
  license_file: LICENSE
  summary: The Time Zone Database (called tz, tzdb or zoneinfo) data
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - mbargull
    - ocefpaf
    - pganssle
