# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: libcurl
  version: 8.3.0
source:
  sha256: 051a217095671e925a129ba9e2ff2e223b44b08399003ba50738060955d010ff
  url: http://curl.haxx.se/download/curl-8.3.0.tar.bz2
build:
  number: 0
  run_exports:
    - libcurl >=8.3.0,<9.0a0
  string: hc52a3a8_0
requirements:
  build:
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 habff3f6_14
    - cctools_osx-arm64 973.0.1 h2f5fd4a_14
    - clang 15.0.7 h694c41f_3
    - clang-15 15.0.7 default_hdb78580_3
    - clang_osx-arm64 15.0.7 h1cd4f45_3
    - clangxx 15.0.7 default_hdb78580_3
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 609 h0fd476b_14
    - ld64_osx-arm64 609 he51b688_14
    - libclang-cpp15 15.0.7 default_hdb78580_3
    - libcxx 16.0.6 hd57cbcb_0
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_3
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 15.0.7 he4b1e75_3
    - openssl 3.1.2 h8a1eda9_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - c-ares 1.19.1 hb547adb_0
    - ca-certificates 2023.7.22 hf0a4a13_0
    - krb5 1.21.2 h92f50d5_0
    - libcxx 16.0.6 h4653b0c_0
    - libedit 3.1.20191231 hc8eb9b7_2
    - libev 4.33 h642e427_1
    - libnghttp2 1.52.0 hae82a92_0
    - libssh2 1.11.0 h7a5bd25_0
    - libzlib 1.2.13 h53f4e23_5
    - ncurses 6.4 h7ea286d_0
    - openssl 3.1.2 h53f4e23_0
    - zlib 1.2.13 h53f4e23_5
    - zstd 1.5.5 h4f39d0f_0
  run:
    - krb5 >=1.21.2,<1.22.0a0
    - libnghttp2 >=1.52.0,<2.0a0
    - libssh2 >=1.11.0,<2.0a0
    - libzlib >=1.2.13,<1.3.0a0
    - openssl >=3.1.2,<4.0a0
    - zstd >=1.5.5,<1.6.0a0
test:
  commands:
    - curl-config --features
    - curl-config --protocols
    - test -f ${PREFIX}/lib/libcurl${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libcurl.a
    - CURL_SSL_BACKENDS=$(curl-config --ssl-backends)
    - if ! echo $CURL_SSL_BACKENDS | grep -q "OpenSSL"; then exit 1; fi
    - if ! echo $CURL_SSL_BACKENDS | grep -q "Secure Transport"; then exit 1; fi
about:
  description: 'Curl is an open source command line tool and library for transferring
    data

    with URL syntax. It is used in command lines or scripts to transfer data.

    '
  dev_url: https://github.com/curl/curl
  doc_source_url: https://github.com/curl/curl/tree/master/docs
  doc_url: https://curl.haxx.se/docs/
  home: http://curl.haxx.se/
  license: curl
  license_family: MIT
  license_file: COPYING
  summary: tool and library for transferring data with URL syntax
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - xylar
